# -*- coding: utf-8 -*-
"""Regre_Logística.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FP_H3sxS3PiMLFc9IjuXF1IoxKc1djzL

# Regresión logística

## Introducción

El objetivo de este archivo es mostrar el desarrollo de regresión logística en el marco de machine learning y el modelo lineal general.

Cuando hablamos de regresión logística nos referimos a una tarea de predicción de una variable con múltiples categorías, lo cual es conocido como un problema de clasificación. En particular en este libro de notas nos restringiremos a la regresión logística binaria, en la que los posibles resultados de la variable predictora son solo dos, y se puede pensar en que la respuesta es una variable binomial.

##Data and business understanding

Trabajaremos con el contexto del archivo de cartera de empresas. Para mantener los libros de nota modulares, repetiré aquí el contexto:
"""

if (!require('caret')) install.packages('caret')
if (!require('ROCR')) install.packages('ROCR')

library(caret)
library(ROCR)
library(ggplot2)
library(readxl)

cartera<-read_excel("carteraguia2017.xlsx")
str(cartera)

"""El archivo contiene datos de clientes de un proveedor de instituciones de salud (IPS), la cartera que presentan y si se han retrasado o no. Se trata entonces de un negocio B2B en el sector de la salud que desea predecir o averiguar indicadores de posibles aumentos y retrasos en su cartera

Entre las variables predictoras se incluyen:


*   Tipo_IPS: De 1 a5, el nivel de complejidad de la institución de salud cliente (1=bajo, 5=alto)

*   MESES: Los meses que la empresa lleva siendo clientes del proveedor.

*   IGUAL_DUEÑO: Número de años en que la IPS ha tenido el mismo dueño.

*   AGNOS_DIRECCION_ACTUAL: Número de años en que la IPS ha estado en la misma dirección.

*   VENTAS_MENS_PROMEDIO: Valor de ventas mensuales promedio de la IPS en millones de pesos.

*   PORC_PASIVOS_VENTA_ANUAL: Porcentaje de pasivos/ venta anual del último balance disponible.


*   CARTERA_ACTUAL_INSUMOS_A: Valor de la deuda con el proveedor en insumos de alta rotación (gasa, jeringas, por ejemplo) en millones de pesos.

*   CARTERA_ACTUAL_INSUMOS_B: Valor de la deuda con el proveedor en insumos de baja rotación (equipos, instrumentos, por ejemplo) en millones de pesos.



La variable a predecir son los RETRASOS, que indican sí el cliente se ha retrasado o no, siendo 1=sí y 0=No.

##Data preparation

Primero vamos a convertir a factores las dos variables que lo requieren: Tipo IPS y retrasos. También vamos a crear variables binarias para los tipos de IPS y luego retirar la variable TIPO IPS.
"""

cartera$TIPOips<-as.factor(cartera$TIPO_ips)
cartera$retrasos<-as.factor(cartera$retrasos)

"""Si se desea se puede realizar una exploración básica de las variables independientes antes de separarlas en bases de entrenamiento y validación, lo que se deja al lector.

De todos modos, es importante ver la proporción de retrasos vs. no retrasos. En caso de que una de las clases, usualmente la clase que más interesa predecir, tenga un porcentaje mucho menor que la otra (digamos, menos del 20%) es necesario un balanceo de la base de datos.
"""

balance<-table(cartera$retrasos)
prop.table(balance)

"""Incialmente no es necesario un balanceo, pero podemos considerarlo más adelante si queremos que el algoritmo “aprenda” más sobre los retrasos.

Creemos bases de entrenamiento y validación
"""

set.seed(1545867)
#aquí se define el tamaño de la muestra, en este caso entrenamiento tendrá el 75% de los casos

sample <- sample.int(nrow(cartera), floor(.75*nrow(cartera)))
cartera.train <- cartera[sample, ]
cartera.test <- cartera[-sample, ]

"""## Modelling

Ahora podemos hacer un modelo de regresión logística basado en pasos sucesivos:
"""

##Modelo
modelo.logit<-glm(retrasos~.,family=binomial,cartera.train)
#trace=0 impide ver todos los detalles de la optimización stepwise
steplogit<-step(modelo.logit, direction="both")
summary(steplogit)

"""La devianza debería disminuir sustancialmente desde la nula hacia la residual.

Los coeficientes de la regresión logística pueden ser sujeto de interpretación en términos de odd ratios.
"""

coeficientes<-steplogit$coefficients
odd_change<-exp(coeficientes)
odd_change_ver<-as.data.frame(odd_change)
odd_change_ver

"""### odd ratios

Los coeficientes, denominados odd ratios indican que:

Cada mes con el mismo dueño, dejando todas las demás variables constantes, reduce al 81.6% el odd base de que el cliente incumpla, es decir, reduce la probabilidad de incumplimiento (la reducción exacta en probabilidad la veremos más adelante).

Cada año en la dirección actual reduce el odd base al 93.6%. Cada millón de venta mensual promedio reduce el odd base al 97.8%

En la otra dirección están las variables que aumentan el incumplimiento: Por cada punto porcentual de pasivo/venta anual aumenta el odd base en 6.7%, mientras que cada millon que adeuda al proveedor en cartera  aumenta el odd base de incumplimiento, cuando es de  baja rotación (A) en 75.8% y es de alta rotación (B) en 14.3%

Para entender mejor los odd ratios es necesario primero tener clara la tasa base. Ese valor es la proporción de éxitos en la base de datos (en este caso siendo éxito un retraso). Esto ya lo obtuvimos en la tabla vista previamente y que aquí repetimos. De allí, podemos calcular un odd base.
"""

#Odd ratios
balance<-table(cartera$retrasos)
prop.table(balance)
oddbase<-prop.table(balance)[2]/prop.table(balance)[1]
oddbase

"""Si el odd base es de 0.29 (y la probabilidad inicial de incumplimiento de 22.65%), podemos multiplicar los odd ratios por esa tase base y luego convertirla a probabilidad:"""

oddfin<-oddbase*odd_change
prob1step<-as.data.frame(oddfin/(1+oddfin))
View(prob1step)

"""De ese modo vemos, por ejemplo, que aumentar un año el cliente en la dirección actual (con todo lo demás constante) reduce la probabilidad de incumplimiento al 21.5%, mientras que el primer millón adicional de cartera en insumos A la aumenta al 33.99%.
Estos aumentos o disminuciones en probabilidad no son lineales. El segundo y tercer año (o el segundo y tercer millón) no genera exactamente el mismo aumento y disminución. De hecho, se genera una curva de tipo “s”.

Creemos una base de datos para ver eso:
"""

#crear matriz vacia
oddprueba<-matrix(,6,29)
probprueba<-matrix(,6,29)

#borrar el intercepto
odd_change2<-odd_change[-1]

#guardar odd base y probabilidad base
oddprueba[,11]<-oddbase
probprueba[,11]<-oddprueba[,11]/(1+oddprueba[,11])

#calcular odds y probabilidades 17 pasos adelante
for (i in 12:29){
  oddprueba[,i]<-oddprueba[,i-1]*odd_change2
  probprueba[,i]<-oddprueba[,i]/(1+oddprueba[,i])
}

#y 10 atrás
for (i in 10:1){
  oddprueba[,i]<-oddprueba[,i+1]/odd_change2
  probprueba[,i]<-oddprueba[,i]/(1+oddprueba[,i])
}

#guardar en un dataframe
probver<-as.data.frame(t(probprueba))
#crear id y graficar: cartera insumos A
probver$id<-seq(1:29)-11
names(probver)<-c("años igual dueño","años dirección actual","ventas promedio", "%pasivo/ venta anual","cartera insumos A", "cartera insumos B", "pasos")
ggplot(probver, aes(x=pasos,y=`cartera insumos A`))+geom_point()+labs(x="millones por encima/debajo de la tasa base",y="probabilidad de default")+scale_x_continuous(breaks=c(-10,-8,-6,-4,-2,0,2,4,6,8,10))+theme_minimal()
#plot(probver$pasos, probver$`cartera insumos A`)

"""## Evaluación

Para la evaluación de un problema de clasificación se utilizan con mucha frecuencia las matrices de confusión, que permiten ver la precision y la exhaustividad (precision and recall)

Las haremos suponiendo que una predicción superior a 0.5 indica incumplimiento, y una predicción inferior o igual a 0.5 indica cumplimiento
"""

#crea el pronostico base de entrenamiento
prontrain<-ifelse(steplogit$fitted.values > 0.5,1,0)
#tabla de confusión y estad?sticas, base de entrenamiento
conftrain<-confusionMatrix(as.factor(prontrain),cartera.train$retrasos, positive = "1")
conftrain$table

as.data.frame(conftrain$byClass)

#crea el pronóstico en validación
probtest<-predict(steplogit,newdata = cartera.test,type='response')
prontest<-ifelse(probtest > 0.5,1,0)
conftest<-confusionMatrix(as.factor(prontest),cartera.test$retrasos, positive = "1")
conftest$table

as.data.frame(conftest$byClass)

"""En la base de datos de prueba, la precisión es del 64.3% y la exhaustividad de 34.6%. La precisión es qué tanto acierta el modelo cuando dice que una empresa generará incumplimiento. La exahustividad es cuántas de las empresas incumplidas son detectadas como tales.UNa combinación de los dos es el F1 score, que para nuestro caso es de 45%. Se puede aumentar la precisión disminuyendo la exhaustividad y viceversa, cambiando simplemente el punto de corte (disminuyéndolo para aumentar precisión o aumentándolo para aumentar exhaustividad)

Para observar ese balance se utiliza la curva COR (o ROC por sus siglas en inglés). Al graficar la curva de todas las posibles combinaciones de falsos positivos (que hablan de la precisión) contra los verdaderos positivos (que hablan de la exhaustividad) podemos darnos una idea de cómo funcionaría el modelo en diferentes puntos de corte. El área bajo la curva dibujada es un indicador adicional de la calidad del modelo
"""

##nuevo sobre precision
cartllev<-cbind(cartera.test,probtest)

corte<-0.05
cartllev$pronostico<-as.factor(ifelse(cartllev$probtest>corte,1,0))
cartllev$error<-as.factor(as.numeric(cartllev$retrasos)-as.numeric(cartllev$pronostico))
ggplot(cartllev,aes(probtest,retrasos, color=error))+geom_point()+geom_vline(xintercept=corte)

corte<-0.5
cartllev$pronostico<-as.factor(ifelse(cartllev$probtest>corte,1,0))
cartllev$error<-as.factor(as.numeric(cartllev$retrasos)-as.numeric(cartllev$pronostico))
ggplot(cartllev,aes(probtest,retrasos, color=error))+geom_point()+geom_vline(xintercept=corte)

corte<-0.8
cartllev$pronostico<-as.factor(ifelse(cartllev$probtest>corte,1,0))
cartllev$error<-as.factor(as.numeric(cartllev$retrasos)-as.numeric(cartllev$pronostico))
ggplot(cartllev,aes(probtest,retrasos, color=error))+geom_point()+geom_vline(xintercept=corte)

corte<-0.25
cartllev$pronostico<-as.factor(ifelse(cartllev$probtest>corte,1,0))
cartllev$error<-as.factor(as.numeric(cartllev$retrasos)-as.numeric(cartllev$pronostico))
ggplot(cartllev,aes(probtest,retrasos, color=error))+geom_point()+geom_vline(xintercept=corte)

#crear objeto de predicciones
pr<-prediction(probtest,cartera.test$retrasos)
#creacion del objeto de la curva
curvaROC<-performance(pr,measure="tpr",x.measure="fpr")

#grafico de la curva
plot(curvaROC)
#calcular el AUC
auc<-performance(pr,measure = "auc")
auc <- auc@y.values[[1]]
#ver el AUC
auc

"""El area bajo la curva es de 80.9%, lo cual está bien por encima del 50% de una predicción al azar.

La curva COR muestra que para lograr un 80% de exhaustividad (tomar acciones sobre el 80% de los incumplidos), tendríamos que aceptar un 26% de falsos positivos (en lenguaje de negocios, tendríamos que “tocar o incomodar” al 26% de clientes que van a ser cumplidos)

De hecho, esos valores exactos son 26.1% y 80.8%. La tabla completa puede obtenerse de la siguiente manera:
"""

fprs<-unlist(curvaROC@x.values)
tprs<-unlist(curvaROC@y.values)
tablaCOR<-as.data.frame(cbind(fprs,tprs))
tablaCOR[70:95,]

"""La curva de ganancias (gain) permite ver a qué porcentaje de la base de datos hay que mirar para obtener un porcentaje dado de casos positivos"""

gain<-performance(pr, "tpr", "rpp")
plot(gain)

"""Vemos que con el 10% de la base de datos con puntajes más altos obtenemos cerca del  25% de los incumplidos (grupo objetivo)

## Evaluación financiera

Los valores de capacidad predictiva (y de error) deben ser vistos a la luz del negocio. Eso significa, usualmente, traducirlos en términos de costo/beneficio.

Ahi suele ser clave trabajar para maximizar la ganancia.

Para ello es importante definir los beneficios que nos trae un acierto y las pérdidas que nos genera un error.

Supongamos que un acierto nos permite ganancias (a 1 año) de 700 (mil pesos) y en cambio un fracaso nos hace perder un primer negocio de aproximadamente 100 (mil pesos). Vamos a suponer que el porcentaje de éxitos posibles es similar al de la base de datos completa.

Podemos crear una base de precisiones y exhaustividades que, basadas en la ecuación vista en clase, nos permitan calcular ganancias para diferentes puntos de corte:
"""

#guardar las exhaustividades y puntos de corte
tablafinan<-performance(pr,measure="rec")
cutoffs<-unlist(tablafinan@x.values)
recalls<-unlist(tablafinan@y.values)

#guardar las precisiones
tablafina2<-performance(pr,measure="prec")
precisions<-unlist(tablafina2@y.values)

#guardar f scores
tablafina3<-performance(pr,measure="f")
fscores<-unlist(tablafina3@y.values)

#crear la tabla conjunta
tablacruce<-as.data.frame(cbind(cutoffs,precisions,recalls,fscores))

#ver precisiones versus exhaustividad
plot(tablacruce$precisions,tablacruce$recalls)

#ver el cutoff que maximiza f score
ggplot(tablacruce, aes(cutoffs,fscores))+geom_point()

#calcular las ganancias
tablacruce$wins<-prop.table(balance)[2]*recalls*(700-(100/precisions))

#pintar las ganancias versus los cutoffs
plot(tablacruce$cutoffs,tablacruce$wins)

#ver las ganancias frente a la precisión
plot(tablacruce$precisions,tablacruce$wins)

"""La primera gráfica nos muestra la relación inversa entre precisiones y exhaustividades.

La segunda gráfica nos muestra el cambio en F score según el punto de corte, donde el punto de corte que máxima el F score es de 25%
La tercera gráfica nos presenta las ganancias (por cliente) contra los puntos de corte, de modo que podemos escoger un punto de corte ideal, el cual, para las ganancias y pérdidas presentadas está cercano a 0.2.

La cuarta gráfica nos muestra la relación de ganancias con precisones, donde es visible que no necesariamente la mayor precisión lleva a la mejor ganancia (por su baja exhaustividad)

Por supuesto, estos resultados dependen de la definición de ganancias y pérdidas. Si el costo de un cliente que incumple, por ejemplo, es del 70% frente a la ganancia que puede traer un cliente cumplido, entonces la precisión actual no es suficiente y debemos cambiar el punto de corte o buscar un balanceo de la base de datos que permita realizar mejores predicciones de incumplidos.
"""

tablaver<-subset(tablacruce, tablacruce$cutoffs>0.13 & tablacruce$cutoffs<0.22)
View(tablaver)

"""## Balanceo

Una posibilidad para aprender más sobre los incumplimientos (1 en la base de datos) es generando muestras de tal modo que la base de entrenamiento tenga 50% de cada clase, y la base de prueba, en lo posible, un porcentaje no tocado de la base de datos con las proporciones originales de cumplimientos e incumplimientos (1s y 0s) . Esto puede hacerse retirando casos positivos de la base de entrenamiento (undersampling) o remuestreándolos de forma que se aumenten hasta alcanzar el balance (oversampling). La generación de muestras debe hacerse obligatoriamente *después* de separar la base de prueba, con el fin de evitar la filtración de datos de entrenamiento hacia prueba.  
Para esto usaremos la librería ROSE que ya trae ambos métodos implementados (aunque el balance tiende a no quedar perfecto, si bien se acerca)
"""

if (!require('ROSE')) install.packages('ROSE')

library(ROSE)

##ajusto el p porque el 50% no está logrando el balance adecuado
cartera.train.over<-ovun.sample(retrasos~.,data=cartera.train,method="over",p=0.49,seed=398)$data
cartera.train.under<-ovun.sample(retrasos~.,data=cartera.train,method="under",seed=398)$data

table(cartera.train$retrasos)

table(cartera.train.over$retrasos)

table(cartera.train.under$retrasos)

prop.table(table(cartera$retrasos))
prop.table(table(cartera.train.over$retrasos))
prop.table(table(cartera.train.under$retrasos))

"""Vemos que la base de entrenamiento queda cerca al  50%-50% de casos, y la de test es la misma original

exploremos
"""

ggplot(cartera.train.under,aes(x=IGUAL_DUENO, y=cartera_actual_insumos_A,color=retrasos))+geom_point()

"""El gráfico es más visible que con la base de datos original, que tendría más puntos de cumplidos que de incumplidos.

Hagamos un modelo con el oversampling:
"""

modelo.balance<-glm(retrasos~.,family=binomial,cartera.train.under)

#trace=0 impide ver todos los detalles de la optimización stepwise
stepbalance<-step(modelo.balance, direction="both", trace=0)
summary(stepbalance)

"""Note que las variables predictoras cambiaron. Cuatro se mantuvieron (pasivos, igual dueño, años en dirección actual y cartera A) pero 2 ya no quedaron en el modelo (ventas promedio y cartera B). Miremos los odds"""

coeficientes2<-stepbalance$coefficients
odd_changeb<-exp(coeficientes2)
odd_changeb

"""Cada año con el mismo dueño disminuyen el odd de ser incumplido al 84.4% , cada millón de cartera A aumenta ese odd en 77.2% y cada punto porcentual de pasivo aumenta el odd en 10.0%. Miremos sus métricas de desempeño en prueba:"""

#crea el pronóstico en validación
probtest2<-predict(stepbalance,newdata = cartera.test,type='response')
prontest2<-ifelse(probtest2 > 0.5,1,0)
conftest2<-confusionMatrix(as.factor(prontest2),cartera.test$retrasos, positive = "1")
conftest2$table

as.data.frame(conftest2$byClass)

"""Nótese que la precisión baja (al 52.6%) pero la exhaustividad sube (al 76.9%). El F score, con punto de corte en 0.5 es de 62.5%, superior al del anterior modelo.

 Y en cuanto a AUC?
"""

#crear objeto de predicciones
pr2<-prediction(probtest2,cartera.test$retrasos)
#creacion del objeto de la curva
curvaROC2<-performance(pr2,measure="tpr",x.measure="fpr")
#grafico de la curva
plot(curvaROC2)

#calcular el AUC
auc2<-performance(pr2,measure = "auc")
auc2f <- auc2@y.values[[1]]
#ver el AUC
auc2f

"""Nuestro AUC ahora es del 82.7% (una leve mejora), y ahora el modelo está sesgado en la búsqueda de incumplidos. ¿Que pasará si se hace el modelo con oversampling?


"""

modelo.balanceover<-glm(retrasos~.,family=binomial,cartera.train.over)
stepbalance2<-step(modelo.balanceover, direction="both", trace=0)
summary(stepbalance2)

probtest3<-predict(stepbalance2,newdata = cartera.test,type='response')
prontest3<-ifelse(probtest3 > 0.5,1,0)
conftest3<-confusionMatrix(as.factor(prontest3),cartera.test$retrasos, positive = "1")
conftest3$table
as.data.frame(conftest3$byClass)

#crear objeto de predicciones
pr3<-prediction(probtest3,cartera.test$retrasos)
#creacion del objeto de la curva
curvaROC3<-performance(pr3,measure="tpr",x.measure="fpr")
#grafico de la curva
plot(curvaROC3)

#calcular el AUC
auc3<-performance(pr3,measure = "auc")
auc3f <- auc3@y.values[[1]]
#ver el AUC
auc3f

"""El modelo incluye más variables (algo más de riesgo de overfitting). Sus métricas son ligeramente mejores que en undersampling en test, con un AUC del 83.6%
En este libro de notas hemos realizado modelos de regresión logística binaria para clasificación, y hemos podido revisar aspectos básicos de evaluación de dichos modelos (incluyendo la parte financiera) y la posibilidad de generar un sesgo de balance para aprender más de una clase que nos interesa más.
"""