# -*- coding: utf-8 -*-
"""Regularización_R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvzUl58OErlLMHBDRgFDTVl50AJfqob6

***Regularización: Redes elásticas***

El objetivo de este Notebook es la presentación de las técnicas de Redes elásticas (incluido Ridge y Lasso) como alternativa específica de regresión que está basada en el proceso de regularización.

**Business understanding**

El problema de determinar precios adecuados (conocido en inglés como pricing) es fundamental dentro de la estrategia de una empresa o firma. No en vano el precio es una de las características de un producto que usualmente ayuda a definir la estrategia.
Dado que los precios usualmente tienen conexión con el valor que los clientes asignan a los productos, se trata de un fenómeno de sicología del consumidor. Por eso los precios incluyen la forma en que los consumidores perciben el valor del producto y sus características, las cuales no son todas necesariamente tangibles.

El caso de estudio se relaciona con un proceso de estimación del precio de vehículos a partir de las características de este, a través del cual trabajaremos el concepto de regularización en un modelo predictivo.

**Data understanding & preparation**

[Para poder descargar los datos](https://sites.google.com/site/cursosalvarado/datafiles)
"""

install.packages("glmnet")
install.packages("caret")

library(glmnet)
library(caret)
library(tidyverse)

carros<-read.csv("carros2011imputado.csv", header=TRUE, sep=";", dec=",")
str(carros)

"""De la estructura de los datos se obtienen las siguientes observaciones que llevarán a transformaciones de preparación de los datos (feature engineering):

1- Si la variable dependiente es el precio, hay 3 precios disponibles. Usar uno de ellos como predictor del otro probablemente no tiene sentido de negocio, porque no es el tipo de característica que va a estar disponible para predecir el precio de un nuevo vehículo. Por eso, dos de ellos serán descartados (dejaremos el precio promedio)

2- Las variables predictoras numéricas están todas asociadas a características físicas del carro. El ID del caso debe ser retirado como variable predictora.

3- Existen un conjunto de datos categóricos (tipo factor en R) que debemos transformar si deseamos que se incluyan como variables predictoras. Los airbags, el tipo de tracción y de transmisión son características no numéricas del vehículo. El tipo de vehículo. y el lugar de fabricación son posibles condicionantes del precio del vehículo también. La marca (fabricante) puede resultar interesante, más aún si tenemos en cuenta que la marca es un intangible muy importante en un vehículo, y hasta ahora ninguna de las variables podía capturar directamente intangibles de los vehículos. El modelo, en cambio, es casi único por cada vehículo (hay 93 modelos) luego es casi una variable identificadora y será descartada. Todas las demás variables categóricas cada una con k categorías a incluir se convertirán en k-1 variables binarias,

Dado que existen más de 20 posibles variables predictoras para un conjunto de tan solo 97 casos, el riesgo de overfitting puede ser grande, más aún si tenemos en cuenta que vamos a crear variables binarias para múltiples variables categóricas y requerimos bases de datos de entrenamiento y validación, incrementando aún más el riesgo mencionado. Todo ello va a implicar decisiones en el modelo y su validación.

Preparemos la base de datos creando las variables dummies necesarias. Vamos a hacer este proceso explícito (R lo hace por defecto) para evaluar la relación número de casos vs número de variables
"""

#guardar los modelos de los carros para interpretación
carmodelos<-carros$modelo
#remover el ID, el modelo y dos de los precios
carros<-within(carros,rm(ID,modelo,precio_basico,precio_equipado))
#crear variables dummy (binarias)
carroswin<-dummyVars("~.",data=carros)
carrosfin<-as.data.frame(predict(carroswin,newdata=carros))
carrosfin2<-within(carrosfin,rm(fabricanteLexus,tipoSporty,tracciónTrasera,transmisión_manualSi,
                                `numero_de_airbagsNo tiene`,
                                `hecho_o_no_en_USAHecho fuera de USA`))
#veamos la dimension final de la base de datos
dim(carrosfin2)

"""Tenemos finalmente una base de datos con 58 variables predictoras y 93 datos (menos de dos casos por variable)

Hagamos una revisión de la posible multicolinealidad de estas variables predictoras. Dado el volumen de variables, un análisis de componentes principales puede ser de interés:
"""

#retiro la variable a predecir
predictores<-cbind(as.matrix(carrosfin2[,1:27]),as.matrix(carrosfin2[,29:59]))

componentescar<-prcomp(predictores, center=TRUE, scale.=TRUE)
summary(componentescar)

"""Los resultados muestran un grado de multicolinealidad medio a alto, con el 20% de las variables representando más del 54% de la variabilidad.

**Modeling**

La multicolinealidad y la baja relación datos a variables hacen de este problema un caso complicado para las regresiones basadas en mínimos cuadrados. Obtengamos un modelo básico y observémoslo.

*Haciendo un modelo clásico*
"""

##entrenamiento y validación 80-20
set.seed(49584)
sample <- sample.int(nrow(carrosfin2), floor(.8*nrow(carrosfin2)))
carros.train <- carrosfin2[sample, ]
carros.test <- carrosfin2[-sample, ]

#haciendo el modelo
modeloaug<-lm(precio_promedio~.,data=carros.train)
modelocarstep<-step(modeloaug,direction="both",trace=0)
summary(modelocarstep)

"""El modelo incluyó 25 variables predictoras. Observe que varias de ellas (11 en total) son no significativas. Una mirada, por ejemplo, a los coeficientes de millas por galón en ciudad y en carretera muestran que tienen signos contrarios, lo que no tiene sentido de negocio y es un clásico signo de multicolinealidad.

La cantidad de variables y la multicolinealidad generan un modelo con inconsistencias de interpretación y con posible *overfitting*

Para comparar la importancia de las variables, vamos a usar los valores t absolutos, lo cual mide su relativa importancia condicionada en las demás variables, y es usada como una métrica clásica de importancia de acuerdo con Grömping, U. (2015). Variable importance in regression models. WIREs Comput Stat 7, 137-152.,
"""

coeficientes<-summary(modelocarstep)$coefficients
coeficientes_base<-as.data.frame(coeficientes)
coeficientes_base <- coeficientes_base %>%
  mutate(Variable = rownames(coeficientes)) %>%
  rename(
    Estimad = Estimate,
    Error = `Std. Error`,
    Valor_t = `t value`,
    Valor_P = `Pr(>|t|)`
  )

# Ordenar por valor t descendente
coeficientes_base <- coeficientes_base %>%
  arrange(desc(abs(Valor_t)))

# Plot usando ggplot2
ggplot(coeficientes_base, aes(x = reorder(Variable, -abs(Valor_t)), y = Valor_t)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Valor_t, 2)), vjust = -0.5) +
  labs(
    title = "Importancia de coeficientes ordenados",
    x = "Variable",
    y = "T"
  ) +
  theme_minimal() +
  coord_flip()

"""**Regularización**

Parte de la problemática es la restricción de que los estimadores deben ser insesgados, y por tanto la suma de los residuales debe ser cero. Eso puede crear una alta varianza en los estimadores, al punto de ver los resultados que observamos.

Puesto que el error en una predicción es la suma de el sesgo y la varianza de la estimación (más el error residual), permitir cierto sesgo que disminuya en mayor proporción la varianza es un mecanismo que claramente puede permitir mejores predicciones.

Para usar la librería glmnet es necesario crear matrices separadas para los predictores y la variable pendiente. En este notebook ya creamos los predictores: falta la variable dependiente
"""

predic.train<-cbind(as.matrix(carros.train[,1:27]),as.matrix(carros.train[,29:59]))
precio.train<-as.matrix(carros.train[,28])

predic.test<-cbind(as.matrix(carros.test[,1:27]),as.matrix(carros.test[,29:59]))
precio.test<-as.matrix(carros.test[,28])

"""Ahora vamos a crear modelos de redes elásticas para observar cómo se comportan para diversos valores del parámetro de penalización lambda.

Es importante anotar que, por defecto, las variables son estandarizadas por el procedimiento.

Con alpha=1 creamos un modelo lasso (penalizado en los valores absolutos de los coeficientes o L1) y con alpha=0 un ridge (penalizado en cuadrados de los coeficientes, o L2). Con 0.5 creamos una red elástica.

El hiperparámetro lambda genera cambios importantes en los modelos, y la escogencia de su valor no siempre es fácil. Veamos, por ejemplo, cómo cambian los coeficientes de una regresión regularizada dependiendo de lambda:
"""

fitlasso<-glmnet(predic.train,precio.train,alpha = 1)
fitridge<-glmnet(predic.train,precio.train,alpha = 0)

#ver la variacion de los coeficientes con el lambda
plot(fitlasso, xvar="lambda")

plot(fitridge, xvar="lambda")

"""Se puede observar como los valores de lambda disminuyen los parámetros desde los de una regresión de mínimos cuadrados (a la izquierda) hasta una penalización alta de coeficientes y, por tanto, un alto sesgo (a la derecha). También puede verse que en el caso de lasso los parámetros se van volviendo cero de manera independiente, mientras en ridge la reducción tiende a ser general (en todos los parámetros)

**Validación cruzada**

¿Cómo escoger lambda? Una buena manera es probar el error que lambda comete en diferentes bases de “prueba”. La idea detrás de la validación cruzada es generar múltiples bases de entrenamiento y validación, creando múltiples modelos en la base de entrenamiento y evaluándolos múltiples veces en la base de validación.

Vamos a hacerlo para el caso de Ridge inicialmente:
"""

foundridge<-cv.glmnet(predic.train, precio.train,alpha=0,nfolds=5)

#grafico lambda vs mse
plot(foundridge)

#veo los lambda minimos
foundridge$lambda.1se

foundridge$lambda.min

"""Este gráfico muestra los errores promedio de cada lambda, junto con sus errores estándar. El valor que minimiza esos errores en promedio es 1.77 (0.65 en el gráfico, donde se ve el logaritmo), pero se suele sugerir (Hastie lo hace) que se utilice un valor más alto, a no más de una desviación estándar del valor del error más bajo, para obtener un modelo más parsimonioso con un error similar, y evadir el overfitting.

**Analizando resultados**

Miremos los resultados usando ese valor de lambda con una desviación estándar más (lambda.1se)
"""

coef(foundridge,s=foundridge$lambda.1se)
verlo<-coef(foundridge,s=foundridge$lambda.1se)

"""Creemos una función para extraer los coeficientes ordenados"""

tener_coeficientes<-function(model, lambda_value) {
  # Extraer coeficientes
  coef_values <- coef(model, s = lambda_value)
  
  # Volver data framen
  coef_df <- as.data.frame(as.matrix(coef_values))
  coef_df <- as.data.frame(cbind(Variable = rownames(coef_df), Coeficiente = coef_df[, 1]))
  
  # Asegurar que la variable no queda en los nombres de fila
  rownames(coef_df) <- NULL
  
  #Ordenar de mayor a menor coeficiente en valor absoluto
  coef_df$Coeficiente<-as.numeric(coef_df$Coeficiente)
  coef_df <- coef_df %>%
    arrange(desc(abs(Coeficiente)))
  
  return(coef_df)
}

"""La aplicamos para el modelo ridge"""

coef_ridge<-tener_coeficientes(foundridge,foundridge$lambda.1se)
View(coef_ridge)

# Plot usando ggplot2
ggplot(coef_ridge, aes(x = reorder(Variable, -abs(Coeficiente)), y = Coeficiente)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Coeficiente, 2)), vjust = -0.5) +
  labs(
    title = "Importancia de coeficientes ordenados",
    x = "Variable",
    y = "Coeficiente"
  ) +
  theme_minimal() +
  coord_flip()

"""Aquí los coeficientes se interpretan en el sentido de sus mayores o menores valores relativos y su signo.
Por ejemplo, entre los tamaños, Midsize y small son los más importantes, el primero aumentando el precio, y el último disminuyéndolo. Entre los fabricantes, las marcas de lujo aumentan el precio (Mercedes benz, Saab, Cadillac, Audi, Infinity) mientras que marcas más populares como Hyundai o Mercury lo disminuyen. Coeficientes más cercanos a cero marcan una baja importancia de la variable.

Mucho más interpretable suele ser un Lasso, porque puede llevar a cero muchos coeficientes:
"""

foundlasso<-cv.glmnet(predic.train, precio.train,alpha=1,nfolds=5)

#grafico lambda vs mse
plot(foundlasso)

#veo los lambda minimos
foundlasso$lambda.1se

foundlasso$lambda.min

coef(foundlasso,s=foundlasso$lambda.min)

coef_lasso<-tener_coeficientes(foundlasso,foundlasso$lambda.min)
# Plot usando ggplot2
ggplot(coef_lasso, aes(x = reorder(Variable, -abs(Coeficiente)), y = Coeficiente)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Coeficiente, 2)), vjust = -0.5) +
  labs(
    title = "Importancia de coeficientes ordenados",
    x = "Variable",
    y = "Coeficiente"
  ) +
  theme_minimal() +
  coord_flip()

"""*El* modelo muy sesgado puede ser  muy simple: un aumento de precio por la relación con los caballos de fuerza y efectos de algunas marcas específicas de lujo o económicas (no todas); pequeños efectos del espacio asiento trasero, el peso, y efectos del tipo de vehiculo. Si se usa el coeficiente de una desviación estándar por encima del mínimo se tiene un modelo con solo 2 predictores (Mercedes y los caballos de fuerza).

Ahora vamos a modelar una red elástica. Vamos a probar valores de alfa dese 0.1 hasta 0.9 para observar cuál puede ser el mejor:
"""

hyper_grid <- expand.grid(
  alpha = c(0.1,0.2,0.3, 0.4,0.5,0.6,0.7,0.8,0.9),       # Búsqueda de grilla en alfa
  lambda = unique(foundlasso$lambda, foundridge$lambda) # Búsqueda de grilla en lambda
)

cross<-trainControl(method="cv",number=10)
redesfit<- train(
  precio_promedio ~ .,
  data = carros.train,
  method = "glmnet",
  tuneGrid=hyper_grid,
  trControl = cross
)

redesfit

plot(redesfit)

redesfit$results

redesfit$bestTune

"""La "mejor# red elástica tiene alpha=0.1. Observe que, de todos modos, hay uina variabilidad asociada en las diferentes particiones (folds), sobre la cual puede hacerse inferencia, y por el tamaño de la base de datos, dicha variabilidad es alta.

**Evaluación**
  
  Finalmente vamos a evaluar los modelos en la base de datos de prueba basados en el RMSE y los criterios de negocio. Lo haremos con la regresión stepwise, lasso, ridge y la mejor red elástica, usando el lambda mínimo.
"""

#red elastica
predicciones1<-predict(redesfit, predic.test)

#ridge
predicciones2<-predict.glmnet(fitridge, predic.test, s=foundridge$lambda.min)

#lasso
predicciones3<-predict.glmnet(fitlasso, predic.test, s=foundlasso$lambda.min)

#stepwise
predicciones4<-predict(modelocarstep,carros.test)

#calcular el RMSE
erroreselastic=sqrt(mean((predicciones1-precio.test[,1])^2))
erroresridge=sqrt(mean((predicciones2-precio.test[,1])^2))
erroreslasso=sqrt(mean((predicciones3-precio.test[,1])^2))
erroresstep=sqrt(mean((predicciones4-precio.test[,1])^2))

errores_compara<-(as.data.frame(rbind(erroreselastic,erroresridge,erroreslasso,erroresstep)))
View(errores_compara)

"""El modelo de red elástica resulta el mejor predictor en la base de datos de prueba, pobablemente con un desempeño muy cercano al ridge. Si bien no se logra una mayor parsimonia (ni el modelo step ni los modelos que llevaron coeficientes a 0 obtuvieron mejores resultados), si parece lograrse una mejor predicción. Dado que los datos están en miles de dólares, la diferencia promedio en precisión entre los dos mejores modelos esta en el orden de los US$149 por predicción (algo cercano al 6%), lo cual, dependiendo de la aplicación, puede o no resultar valioso. El modelo lasso es quizás demasiado simple y comete errores mayores, con errores entre los cientos y los miles de dólares en promedio, lo que los descarta como candidatos viables. Sin embargo, un modelo sesgado y simple como Lasso resulta superior al stepwise. En el modelo step es difícil saber o entender el efecto específico de cada variable independiente, en parte por la falta de estandarización y en parte por los problemas mencionados de multicolinealidad y parte por la baja relación casos/variables. Veamos, en el modelo ganador, el tamaño relativo y signo de los coeficientes para darnos idea de la importancia relativa de las variables en nuestro modelo final:"""

fitelastic<-glmnet(predic.train,precio.train,alpha = 0.1,lambda=2.515709)
coef_elastic<-tener_coeficientes(fitelastic,2.515709)
# Plot usando ggplot2
ggplot(coef_elastic, aes(x = reorder(Variable, -abs(Coeficiente)), y = Coeficiente)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Coeficiente, 2)), vjust = -0.5) +
  labs(
    title = "Importancia de coeficientes ordenados",
    x = "Variable",
    y = "Coeficiente"
  ) +
  theme_minimal() +
  coord_flip()

"""**Conclusión**
  
  Los modelos regularizados pueden ser una alternativa a los modelos insesgados para mejorar la predictibilidad, particularmente en entornos de baja razón casos/variables o con multicolinealidad. La interpretación de los resultados tiene cambios importantes que deben tenerse en cuenta. La idea de la regularización puede aplicarse a múltiples tipos de modelos que estén buscando minimizar una función de error, lo que la hace altamente aplicable en machine learning.

**Referencias**
  Grömping, U. (2015). Variable importance in regression models. WIREs Comput Stat 7, 137-152.,
"""