# -*- coding: utf-8 -*-
"""Cluster_k_means_R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13o8gxBzgE7MbjQaq1mCmCfhzqg2HBxxF

#Cluster k-medias

El objetivo de este notebook es presentar un proceso de segmentación de clientes en telecomunicaciones a partir del algoritmo k-medias
##Definición de variables - Business & data understanding

Para ello importaremos un archivo con información para esa posible segmentación.
"""

install.packages("psych")
install.packages("readxl")
install.packages("reshape2")
install.packages("fpc")
install.packages("vcd")

library("cluster")

install.packages("reshape2")

library(readxl)
cell<-read_excel("cellsegmentation.xlsx")
str(cell)

"""El archivo contiene un grupo de variables demográficas (edad, género, región, casado, jubilado, y al final, ingreso en miles de pesos) y un grupo de variables de consumo: minutos a números preferidos y no preferidos, consumos adicionales, valor mensual pagado por equipo en dólares, gigabytes gastados de internet, si tiene o no tiene productos adicionales (telefonía fija, internet en casa, larga distancia, número oculto) y si recibe o no factura electrónica.

La segmentación de clientes debe hacerse por necesidades. Las variables de consumo son probablemente mejores indicadores de las necesidades que la demografía (aunque consumo, demografía y necesidades pueden estar correlacionadas). Sería interesante hacer una segmentación por consumos y luego perfilar los grupos de forma demográfica para definir estrategias.

Sin embargo, a la hora de definir una métrica de distancia, la combinación de variables de consumo binarias y escalares se dificulta.

Una posible aproximación con las variables binarias es crear una variable que indique el número de servicios adicionales que se tienen. La factura electrónica se puede dejar para perfilar como posible medio para alcanzar al segmento.

Miremos las variables escalares:
"""

library(psych)
psych::describe(cell[,6:10])

par(mfrow=c(2,3))
hist(cell$minutos_preferido)
hist(cell$adicionales)
hist(cell$equipo_dolares)
hist(cell$minutos_no_preferido)
hist(cell$internet_gigas)

"""En todas las variables (excepto minutos preferido) el mínimo es cero. De hecho en los histogramas se observa que hay porcentajes de clientes variables que simplemente no tienen el servicio o no lo consumen. En los promedios es destacable que el consumo fuera de preferidos es cercano a la tendencia central de consumo en preferidos. Las variabilidades son altas (CV´s cercanos o mayores a 100% en todas las variables), lo cual puede ser algo bueno con miras a la creación de grupos distintos. También son visibles asimetrías positivas mayores que 1 en todas las variables (excepto equipo en dólares), lo que marca la presencia de pequeños grupos de consumo extremo versus grandes grupos de bajo consumo. De hecho, las curtosis son todas grandes, (excepto por equipo en dólares) lo que implica la presencia de valores extremos.

Para disminuir la presencia de atípicos (que afectarían a k medias) puede ser una buena idea aplicar de manera adecuada un logaritmo natural a las variables.

##Data preparation

En la preparación de datos se siguieron los pasos explicados a continuación:

    Obtención de una variable que indique número de servicios adicionales.
    Aplicación de reducción de atípicos donde sea necesario (logaritmo natural de (1+x) para tener en cuenta los ceros o valores menores que cero).
    Ensamble de las variables finales en la base de datos.
    Estandarización de las variables para poder usar distancia euclídea.

"""

#variable de servicios adicionales
cell$servicios<-cell$fijo+cell$largadistancia+cell$internetcasa+cell$numoculto
#reducción de atípicos
##obtener las variables a reducir
cell3<-cell[,c(6,7,9,10)]
#obtener el logaritmo de 1+x
cell4<-apply(cell3,2,log1p)
#ensamble final
cellfin<-as.data.frame(cbind(cell4,cell$servicios, cell$equipo_dolares))
colnames(cellfin)[5:6]<-c("servicios","equipo_dolares")
#estandarizar
cellfins<-as.data.frame(scale(cellfin))
#revisar descriptivos
psych::describe(cellfins)

par(mfrow=c(1,3))
hist(cellfins$minutos_preferido)
hist(cellfins$adicionales)
hist(cellfins$minutos_no_preferido)

"""Al revisar se observa que la transformación fue en su mayor parte efectiva (mínimos y máximos cerca de 3 desviaciones estándar, kurtosis ya no tan positivas) aunque en algunos casos con mejores resultados que en otros (por ejemplo, en minutos preferido mejor que en minutos de no preferido).
##Modelación

En la modelación si se va a utilizar el algoritmo k-medias entonces primero se debe hacer la selección del valor de k

###Selección de k

Aunque criterios de negocio pueden aplicar en esta selección (p.e., cuántas estrategias distintas puedo manejar) también hay algunos mecanismos que permiten proponer un valor de k. El mecanismo descriptivo clásico es el gráfico de las sumas de cuadrados dentro de los clústeres frente al número de clústeres, llamado gráfico de codo. En el momento en que la curva cambia de pendiente (se ve un codo), las reducciones de cuadrados internos dejan de ser tan buenas y se puede escoger ese valor como un k sugerido. En el siguientre código vamos a hacer ese gráfico entre 2 y 15 clústeres:
"""

#utilizo una semilla para replicar resultados
set.seed(5935)
#calculo la suma de cuadrados total
wss <- (nrow(cellfins)-1)*sum(apply(cellfins,2,var))
#calculo para cada solución de clustering
for (i in 2:15) wss[i] <- sum(kmeans(cellfins,
                                     centers=i, nstart=10)$withinss)
plot(1:15, wss, type="b", xlab="Número de Clústeres",
     ylab="Suma de cuadrados within")

library("cluster")
library("fpc")

# Evaluar usando el criterio ASW (average sillouethe width)
set.seed(2) #Para evitar aleatoriedad en los resultados
clustering.asw <- kmeansruns(cellfins,krange=2:15,criterion="asw",iter.max=100, runs= 100,critout=TRUE)
clustering.asw$bestk

"""Este criterio sugiere 2 clústeres

El criterio sugerido por Hastie et al. (2017) es usar la estadística Gap. Obtengámosla:
"""

#Evaluar con gap statistic
#mira el minimo k tal que el gap sea mayor que el gap de k+1 restado de su desviacion
gscar<-clusGap(cellfins,FUN=kmeans,K.max=15,B=60)
gscar

"""La estadística gap sugiere como número de clústeres el valor de 5.

Como es visible los métodos pueden no coincidir, por lo que es necesario utilizar criterios empíricos para definir. Dado que el criterio de silueta vuelve a subir en 5, y 5 es una buena opción en el gráfico de codo así como en el estadístico gap, escogemos 5.
###Ejecución e interpretación de resultados

Al ejecutar k-medias es importante la estandarización, la reducción de atípicos y la definición de inicializaciones de los centros. Por ello se recomienda hacer múltiples inicializaciones para buscar el mejor resultado. En este caso vamos a inicializar 10 veces. Así mismo hay un número máximo de iteraciones permitidas (el algoritmo podría quedarse iterando por mucho tiempo, en teoría). La práctica indica que 20 iteraciones suelen ser suficientes. De todas formas pueden aumentarse en caso de que el algoritmo no converja.

Una vez ejecutado vamos a ver:

    el número de iteraciones que tomó
    el tamaño de los 5 grupos
    los centros de los grupos para la interpretación

"""

#ejecución de k-means
set.seed(45390)
cellcluster<-kmeans(cellfins,centers=5,nstart=10,iter.max=20)
#tamaño de grupos
cellcluster$size

#numero de iteraciones
cellcluster$iter

"""No existen tamaños de grupo pequeños, por lo que no parece que algun atípico haya dominado o se haya apoderado de un grupo. 7 iteraciones fueron suficientes para obtener el resultado final."""

#centros de grupos
cellcluster$centers

install.packages("reshape2")

library(ggplot2)
library(reshape2)
centrosg<-as.data.frame(cellcluster$centers)
centrosg$grupo<-as.factor(rownames(centrosg))
centrosheat<-reshape2::melt(centrosg)
colnames(centrosheat)<-c("grupo","variable","centroide")
ggplot(centrosheat,aes(x=grupo,y=variable,fill=centroide, label=sprintf("%0.2f", round(centroide, digits=2))))+geom_tile()+scale_fill_distiller(palette="RdBu")+geom_text()

"""Para leer los centros, consideremos que se trata de valores estándares (algunos de ellos de logaritmos). De ese modo, valores positivos implican mayor consumo que la media, y negativos menor que la media. La magnitud indica el número de desviaciones estándar. No debemos esperar valores de 3 o más para decir que el consumo es alto, porque se trata del centro de un grupo, por lo que se esperan valores más moderados.

Basándonos en una desviación estándar tendríamos:

    El grupo 5 tiene bajo consumo de adicionales.
    El grupo 3 es de alto consumo de adicionales e internet.
    El grupo 2 es un grupo de bajo consumo, particularmente en sus minutos a no preferidos.
    El grupo 4 se caracteriza por alto consumo de adicionales.
    El grupo 1 es de alto consumo de internet, tiene combos o servicios con la empresa y paga más que el promedio por equipos.

##Perfilamiento

Una vez definidos los grupos, podemos perfilarlos demográficamente para plantear estrategias.
"""

#guardar el cluster de pertenencia
cell$grupo<-cellcluster$cluster
library("vcd")
mosaic(~grupo + jubilado ,data=cell,
       legend=TRUE, shade=TRUE)

mosaic(~grupo + genero ,data=cell,
       legend=TRUE, shade=TRUE)

boxplot(log(ingreso_miles)~grupo, data=cell)

boxplot(Edad~grupo, data=cell)

"""No se observan diferencias por género. Se observa que los jubilados tienden a estar en el grupo 4 y no en el grupo 3. Así mismo en el grupo 3 están los más jóvenes (lo cual coincide) y los grupos 1 y 5 son los de mayores ingresos (y, por tanto, mayor consumo).

El gráfico a continuación permite ver los clientes proyectados en sus dos dimensiones principales (mediante componentes principales), lo que permitiría explicar o visualizar parcialmente los grupos
"""

clusplot(cellfins,cellcluster$cluster, color=TRUE)

"""Para validar los resultados, una opción indirecta es calcular la robustez, en este caso vista como qué tanto variarían los resultados ante pequeñas modificaciones en los datos. Para ello usamos clusterboot."""

#validar resultados- consistencia
kclusters <- clusterboot(cellfins,B=10,clustermethod=kmeansCBI,k=5,seed=5)
#la validacion del resultado. >0.75 o .85 muy bueno; <.6 malo
kclusters$bootmean

"""Los resultados muestran 3 clusteres bastante coherentes, un grupo en niveles intermedios, y un grupo de coherencia baja, lo que puede sugerir explorar la opción de 4 clústeres."""
