# -*- coding: utf-8 -*-
"""Clustering_kmeans_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yiB9ZPI2Kwo5epgAIDqGRX149BJl9Me

#Cluster k-medias

El objetivo de este notebook es presentar un proceso de segmentación de clientes en telecomunicaciones a partir del algoritmo k-medias
##Definición de variables - Business & data understanding

Para ello importaremos un archivo con información para esa posible segmentación.
"""

import numpy as np
import pandas as pd

cell=pd.read_excel("cellsegmentation.xlsx")
cell.info()

"""El archivo contiene un grupo de variables demográficas (edad, género, región, casado, jubilado, y al final, ingreso en miles de pesos) y un grupo de variables de consumo: minutos a números preferidos y no preferidos, consumos adicionales, valor mensual pagado por equipo en dólares, gigabytes gastados de internet, si tiene o no tiene productos adicionales (telefonía fija, internet en casa, larga distancia, número oculto) y si recibe o no factura electrónica.

La segmentación de clientes debe hacerse por necesidades. Las variables de consumo son probablemente mejores indicadores de las necesidades que la demografía (aunque consumo, demografía y necesidades pueden estar correlacionadas). Sería interesante hacer una segmentación por consumos y luego perfilar los grupos de forma demográfica para definir estrategias.

Sin embargo, a la hora de definir una métrica de distancia, la combinación de variables de consumo binarias y escalares se dificulta.

Una posible aproximación con las variables binarias es crear una variable que indique el número de servicios adicionales que se tienen. La factura electrónica se puede dejar para perfilar como posible medio para alcanzar al segmento.

Hagamos una descriptiva a las variables:
"""

cell.iloc[:,[5,6,7,8,9]].describe()

"""las variables que más nos interesan van desde minutos preferido hasta Internet gigasd. Miremos su histograma."""

from matplotlib import pyplot as plt

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(cell["minutos_preferido"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(cell["adicionales"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(cell["equipo_dolares"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(cell["minutos_no_preferido"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(cell["internet_gigas"])

"""En todas las variables (excepto minutos preferido) el mínimo es cero. De hecho en los histogramas se observa que hay porcentajes de clientes variables que simplemente no tienen el servicio o no lo consumen. En los promedios es destacable que el consumo fuera de preferidos es cercano a la tendencia central de consumo en preferidos. Las variabilidades son altas (CV´s cercanos o mayores a 100% en todas las variables), lo cual puede ser algo bueno con miras a la creación de grupos distintos. También son visibles asimetrías positivas mayores que 1 en todas las variables (excepto equipo en dólares), lo que marca la presencia de pequeños grupos de consumo extremo versus grandes grupos de bajo consumo. De hecho, las curtosis son todas grandes, (excepto por equipo en dólares) lo que implica la presencia de valores extremos.

Para disminuir la presencia de atípicos (que afectarían a k medias) puede ser una buena idea aplicar de manera adecuada un logaritmo natural a las variables.

##Data preparation

En la preparación de datos se siguieron los pasos explicados a continuación:

    Obtención de una variable que indique número de servicios adicionales.
    Aplicación de reducción de atípicos donde sea necesario (logaritmo natural de (1+x) para tener en cuenta los ceros o valores menores que cero).
    Ensamble de las variables finales en la base de datos.
    Estandarización de las variables para poder usar distancia euclídea.

"""

cell["servicios"]=cell["fijo"]+cell["largadistancia"]+cell["internetcasa"]+cell["numoculto"]

transformar=cell.iloc[:,[5,6,8,9]].copy()
transformar=transformar.apply(np.log1p)
transformar.info()

paracluster=pd.concat([transformar,cell["servicios"],cell["equipo_dolares"]], axis=1)

paracluster.describe()

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(paracluster["minutos_preferido"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(paracluster["adicionales"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(paracluster["minutos_no_preferido"])

fig, ax = plt.subplots(figsize =(10, 7))
ax.hist(paracluster["internet_gigas"])

from sklearn.preprocessing import StandardScaler
escalando=StandardScaler()
paraclusterz = escalando.fit_transform(paracluster)
paraclusterzfin=pd.DataFrame(paraclusterz, columns=list(paracluster.columns))
display(paraclusterzfin)

"""Al revisar se observa que la transformación fue en su mayor parte efectiva (mínimos y máximos cerca de 3 desviaciones estándar, kurtosis ya no tan positivas) aunque en algunos casos con mejores resultados que en otros (por ejemplo, en minutos preferido mejor que en minutos de no preferido).
##Modelación

En la modelación si se va a utilizar el algoritmo k-medias entonces primero se debe hacer la selección del valor de k

###Selección de k

Aunque criterios de negocio pueden aplicar en esta selección (p.e., cuántas estrategias distintas puedo manejar) también hay algunos mecanismos que permiten proponer un valor de k. El mecanismo descriptivo clásico es el gráfico de las sumas de cuadrados dentro de los clústeres frente al número de clústeres, llamado gráfico de codo. En el momento en que la curva cambia de pendiente (se ve un codo), las reducciones de cuadrados internos dejan de ser tan buenas y se puede escoger ese valor como un k sugerido. En el siguientre código vamos a hacer ese gráfico entre 2 y 15 clústeres:
"""

from sklearn.cluster import KMeans
import matplotlib
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
kmeans = KMeans(init = "k-means++",n_clusters=20)
kmeans.fit(paraclusterzfin)
silhouette_score(paraclusterzfin, kmeans.labels_)

from sklearn.cluster import KMeans
import matplotlib
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score

sse=[]
silueta=[]
for k in range(1, 20):
  kmeans = KMeans(init = "k-means++",n_clusters=k)
  kmeans.fit(paraclusterzfin)
  sse.append(kmeans.inertia_)
  if k>1:
    silueta.append(silhouette_score(paraclusterzfin, kmeans.labels_))


import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")
plt.plot(range(1, 20), sse)
plt.xticks(range(1, 20))
plt.xlabel("Numero de Clusters")
plt.ylabel("Suma de cuadrados")
plt.title('Gráfico de codo')
plt.show()

silueta[0:19]

"""Como es visible los métodos pueden no coincidir, por lo que es necesario utilizar criterios empíricos para definir. Dado que el criterio de silueta vuelve a subir en 4, y 5 es una buena opción en el gráfico de codo escogemos entre esos dos 5.
###Ejecución e interpretación de resultados

Al ejecutar k-medias es importante la estandarización, la reducción de atípicos y la definición de inicializaciones de los centros. Por ello se recomienda hacer múltiples inicializaciones para buscar el mejor resultado. En este caso vamos a inicializar 10 veces. Así mismo hay un número máximo de iteraciones permitidas (el algoritmo podría quedarse iterando por mucho tiempo, en teoría). La práctica indica que 20 iteraciones suelen ser suficientes. De todas formas pueden aumentarse en caso de que el algoritmo no converja.

Una vez ejecutado vamos a ver:

    el número de iteraciones que tomó
    el tamaño de los 5 grupos
    los centros de los grupos para la interpretación

"""

modeloclusterk=KMeans(init = "k-means++",n_clusters=5,n_init=12)
modeloclusterk.fit(paraclusterzfin)
modeloclusterk.n_iter_

cell["grupo"] = modeloclusterk.labels_
cell.grupo.value_counts()

"""No existen tamaños de grupo pequeños, por lo que no parece que algun atípico haya dominado o se haya apoderado de un grupo. 10 iteraciones fueron suficientes para obtener el resultado final."""

centros=pd.DataFrame(modeloclusterk.cluster_centers_,columns=list(paraclusterzfin.columns))
display(centros)

"""Para leer los centros, consideremos que se trata de valores estándares (algunos de ellos de logaritmos). De ese modo, valores positivos implican mayor consumo que la media, y negativos menor que la media. La magnitud indica el número de desviaciones estándar. No debemos esperar valores de 3 o más para decir que el consumo es alto, porque se trata del centro de un grupo, por lo que se esperan valores más moderados.

Basándonos en una desviación estándar tendríamos:
  Grupo 0 de bajo consumo, en particular a no preferido.
  Grupo 1 tiene alto consumo de adicionales e internet.
  Grupo 2 tiene el más alto consumo de preferidos (aunque no alcanza la desviaicón estándar)
  Grupo 3 tiene alto consumo de servicios, internet y equipo.
  Grupo 4 tiene alto consumo de adicionales
   El grupo 5 tiene bajo consumo de adicionales.

Se puede revisar fácilmente los valores centroides sacando el promedio de las características de cada cluster.
"""

cell.groupby('grupo').mean()

list(cell.columns)

"""##Perfilamiento

Una vez definidos los grupos, podemos perfilarlos demográficamente para plantear estrategias.
"""

cruzada=pd.crosstab(cell["jubilado"],cell["grupo"])
cruzada

from scipy import stats
stats.chi2_contingency(cruzada)

"""Ejercicio: hacerlo para genero"""

import plotly.express as px
fig = px.box(cell, x="grupo", y="Edad")
fig.show()

"""Ejercicio: hacerlo para el ingreso. ¿es necesaria una transformación?"""