# -*- coding: utf-8 -*-
"""jerarquico_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfAVefTdMRq2FTCrzZIA0smQlKUKWpui

#Cluster jerárquico
El objetivo del archivo es elaborar un cluster jerárquico. Para ello utilizaremos una base de datos de países del mundo. Adicionalmente, instalaremos en colab las librerías necesarias.
"""

# Importar librerias requeridas
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

mundo=pd.read_excel("mundo2014ampliado.xlsx")
mundo.info()

"""##Definición de variables- Business & data understanding

Por el teorema del patito feo sabemos que la elección de las variables a utilizar no es neutra, luego debemos ponernos en una posición u objetivo específico que nos guíe. Supongamos que somos un organismo multilateral con alguna capacidad de apoyo a los países americanos, y resulta de importancia focalizar la ayuda por grupos de países según sus necesidades. A partir de ello ¿qué variables escogería?

Si se piensa en que el objetivo es llevar una vida larga, sana, educada y en riqueza se podría decir que el PIB per cápita me habla de la riqueza actual (aunque quizás falte el índice GINI), la esperanza de vida me sirve para medir la vida larga, y el tiempo de escolarización puede ser un proxy de la educación. El crecimiento del PIB y la tasa de fertilidad son más discutibles, aunque el primero me habla de la dinámica actual del país y la segunda tiende a estar correlacionada con el desarrollo (Bryant, J., 2007). En cambio, me inclinaré por descartar las variables de población y PIB pues no me hablan de las necesidades específicas del país.
##Data preparation

Vamos entonces a seleccionar de la base de datos lo que necesitamos.
"""

america=mundo[mundo["america"]==1]
america.shape

americafin=america.iloc[:,[2,3,6,7,8]]
display(americafin)

"""Ejercicio: descripción de los datos

Lo siguiente es calcular una métrica de distancia. Vamos a utilizar la distancia euclidea. Para ello primero tenemos que estandarizar los datos, con el fin de evitar el problema de las diferentes unidades de las variables.
"""

from sklearn.preprocessing import StandardScaler
escalando=StandardScaler()
americaz = escalando.fit_transform(americafin)
americazfin=pd.DataFrame(americaz, columns=list(americafin.columns))
americazfin.set_index(america["Country"],inplace=True)
display(americazfin)

"""##Modelado

Para crear los clústeres jerárquicos el siguiente paso es escoger un mecanismo de unión de los clusteres.

Vamos a revisar la unión completa (* complete linkage*) y la única (*single linkage*) así como la promedio (*average linkage*)

###Utilizar el dendograma para explorar posibilidades

Los dendrogramas ayudan a mostrar las progresiones a medida que se fusionan los grupos. Es un diagrama de ramificación que demuestra cómo cada clúster se compone de ramificaciones en sus nodos secundarios. Empecemos con complete.
"""

from scipy.cluster.hierarchy import dendrogram, linkage
dendo_complete = linkage(americazfin,method="complete")
plt.figure(figsize=(20,10))
#El primer parámetro pasa los enlaces creados previamente, el parámetro truncate_mode permite truncar el dendograma para su mejor visualización
dendrogram(dendo_complete, labels=america["Country"].tolist(),leaf_rotation=45, leaf_font_size=10)
plt.xlabel('Paises')
plt.ylabel('Distancia')
plt.suptitle("DENDROGRAMA ENLACE COMPLETO",fontsize=18)
plt.show()

"""Hagamos una comparación de nuestors resultados con simpoler"""

dendo_single = linkage(americazfin,method="single")
plt.figure(figsize=(20,10))
#El primer parámetro pasa los enlaces creados previamente, el parámetro truncate_mode permite truncar el dendograma para su mejor visualización
dendrogram(dendo_single, labels=america["Country"].tolist(),leaf_rotation=45, leaf_font_size=10)
plt.xlabel('Paises')
plt.ylabel('Distancia')
plt.suptitle("DENDROGRAMA ENLACE SINGLE",fontsize=18)
plt.show()

"""Se pueden observar diferencias interesantes entre los dos métodos.

El método complete busca hacer siempre grupos más compactos mientras single solo une por el punto más cercano. En los grupos iniciales y los finales el resultado tiende a ser el mismo, pero en los grupos intermedios se generan diferencias.

En nuestro caso, Haití es claramente un país diferente, mientras USA y Canadá hacen también un grupo aparte. La diferencia está en la forma en que se unen los demás países.

Argentina, por ejemplo, se clasifica en diferentes grupos. En single, Uruguay, Bolivia, Guatemala y El Salvador se unen lentamente al final al grupo, mientras que en complete se arman dos grupos (de Chile a Uruguay y de Bolivia a Nicaragua) que se unen al final. Si lo que queremos es grupos de países para una única estrategia de apoyo, quizás complete sea nuestra metodología.

Observe que, al no incluir la población, México y Brasil se ubican en ambos casos en lugares diferentes. México es más cercano a Perú, mientras que Brasil es más cercano a Colombia.
Average es un punto intermedio. Veámoslo:
"""

dendo_average = linkage(americazfin,method="average")
plt.figure(figsize=(20,10))
#El primer parámetro pasa los enlaces creados previamente, el parámetro truncate_mode permite truncar el dendograma para su mejor visualización
dendrogram(dendo_average, labels=america["Country"].tolist(),leaf_rotation=45, leaf_font_size=10)
plt.xlabel('Paises')
plt.ylabel('Distancia')
plt.suptitle("DENDROGRAMA ENLACE AVERAGE",fontsize=18)
plt.show()

"""Una vez escogido un método y número de clusteres (supongamos que se toma complete con 6 grupos), se hace la partición definitiva.
En el código siguiente, se importa la clase <b>AgglomerativeClustering</b> de la biblioteca <b>sklearn.cluster</b>. El número de clusters se establece en 3 utilizando el parámetro <b>n_clusters</b> mientras que la <b>affinity</b>, que es la función de distancia, se establece en "euclidiana" (distancia entre los puntos de datos).
"""

from sklearn.cluster import AgglomerativeClustering
clustercomplete = AgglomerativeClustering(n_clusters=6, affinity="euclidean", linkage="complete")
clustercomplete.fit_predict(americazfin)

"""A partir de aquí, podemos realizar análisis similares a los obtenidos previamente en clustering. POr ejemplo: Contar países por grupos."""

america["grupos"] = clustercomplete.labels_
america.grupos.value_counts()

"""Calcular las medias"""

america.groupby('grupos').mean()

"""Revisar pór parejas de variables lo que está ocurriendo con los paises."""

fertil=america["Fertility_rate"].tolist

fertil=america["Fertility_rate"].tolist
pgr=america["Pib_growth"].tolist
country=america["Country"].tolist
fig, ax = plt.subplots()
ax.scatter(america["Fertility_rate"] ,america["Pib_growth"], c=clustercomplete.labels_, cmap="rainbow")

for i, txt in enumerate(america.Country):
    ax.annotate(txt, (america.Fertility_rate.iat[i], america.Pib_growth.iat[i]))

plt.title('Cluster=6, con complete')
plt.xlabel('tasa de fertilidad')
plt.ylabel('crecimiento del PIB')

"""Ejercicio: graficar otras 2 variables, y cambiar a otro método de linkage para observar resultados."""