# -*- coding: utf-8 -*-
"""Descriptiva_en_R_current.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AidUlPqO5uOpOgNyM-XYkzkPB3QuSfbV

#EJERCICIO DE DESCRIPTIVA BÁSICA
##Objetivo
Revisar aspectos estadísticos e interpretativos de los análisis descriptivos en un ejercicio sencillo
##Librerías
A continuación instalaremos o cargaremos las librerías necesarias para nuestro trabajo: readxl para leer archivos de Excel, psych para descriptiva, y e1071
"""

install.packages(c("psych","e1071"))
library(psych)
library(readxl)
library(e1071)

install.packages("DataExplorer")

install.packages(c("GGally","ggmosaic","summarytools"))

"""##Importación de datos en archivos de texto
Una vez ubicados los archivos a importar en el directorio de trabajo, se puede proceder a la importación. En este caso importaremos un archivo separados por comas (csv) con el que trabajaremos



"""

cartera<-read.csv("cartera.csv", header=TRUE, sep=";", dec=",")

"""Nótese que hemos establecido que el archivo tiene los nombres de las variables en el encabezado (header=TRUE) y que el separador es “;”(sep=“;”) y el separador de decimales es la coma (dec=“,”), todo lo cual puede o no ser necesario dependiendo del archivo que se tenga.

El archivo contiene datos de clientes de un proveedor de instituciones de salud (IPS), la cartera que presentan y si se han retrasado o no. Se trata entonces de un negocio B2B en el sector de la salud que desea predecir o averiguar indicadores de posibles aumentos y retrasos en su cartera

##Lectura de archivos de Excel
Ahora sí podemos leer el archivo Excel requerido con una función del paquete readxl y vemos sus primeras lineas con la instrucción “head”
"""

telco<-read_excel("services2.xls")
head(telco)

"""El archivo contiene 3 variables de clientes de una empresa de telefonía móvil. Sus minutos de consumo, su valor de factura, y su propensión a dejar la empresa (churn).
##Tipos de variables y modificaciones a los mismos

Si bien hay múltiples tipos de datos en R, es necesario familiarizarse inicialmente con dos: Categóricos (factor) y escalares (num o numeric). Se puede usar la función str para conocer los tipos de datos de toda la base de datos
"""

str(cartera)

"""En esta base de datos tenemos variables tipo int (entero), tipo num( numérico) y tipo factor (categóricos). Estos últimos se marcan con los niveles o categorías que tienen. Si se quiere ver la clasificación de una sola variable se usa"""

class(cartera$yearsadress)
class(cartera$retrasos)

"""La variable yearsadress, que representa los años en la dirección actual, está mal clasificada como categórica cuando debe ser numérica. La variable retrasos, al ser binaria, puede ser reclasificada como categórica. Hagámoslo:"""

cartera$yearsadress<-as.numeric(cartera$yearsadress)
cartera$retrasos<-as.factor(cartera$retrasos)

"""Ahora estamos listos para realizar algunos análisis a nuestros archivos.
##Descriptiva básica en R
###Resumen básico y selección de subconjuntos

Básicamente cualquier modelo o función estadística en R tiene al menos dos funciones: un resumen (summary) y un gráfico (plot). Pero miremos las diferencias entre estas 3 instrucciones:
"""

summary(telco)
plot(telco$bill)

"""Como podemos ver, la instrucción summary sobre una variable obtiene los valores mínimo, máximo y los cuartiles de la variable. Con estos valores se puede revisar si tien sentido o no el contexto del negocio los valores. Por ejemplo, el score que es una propensión a retirarse de la empresa (churn) está entre 0 y 100 (más exactamente entre 16.7 y 83.45), lo que tiene sentido. La variable bill que representa la facturación, no puede estar en pesos dados sus valores (está en dólares). El consumo en minutos puede o no tener sentido dependiendo de la lógica de negocio.

Aunque el gráfico no es muy informativo, si que son visibles algunos datos atípicos de facturación.
###medidas estadísticas: Tendencia central, dispersión y forma
"""

attach(telco)
mean(bill)
median(bill)
mean(bill, trim=0.2)

"""Se observa una diferencia llamativa entre media y mediana; la media recortada implica datos extremos de facturación, como ya habíamos visto. Esta tendencia central es tambien un posible indicador/meta de negocio: estamos por encima o por debajo de la facturación media que esperamos?

Ahora vamos a obtener un grupo de medidas de dispersión:
"""

range(bill)
var(bill)
sd(bill)
mad(bill)

"""La desviación estándar luce alta, mucho más alta que la desviación media o mad, lo que corrobora nuestra impresión de atípicos. Sin embargo para saber qué tan alta es la dispersión, con frecuencia se compara la desviación estándar con la media, mediante el coeficiente de variación si las variables son claramente superiores a cero. Sin embargo R no tiene construída una función para el coeficiente de variación (CV). Creéemoslo:"""

cv=(100*sd(bill))/mean(bill)
cv

"""Pero si deseamos usarlo en múltiples ocasiones, lo mejor es crear una función:"""

CV <- function(var){(sd(var)/mean(var))*100}
CV(bill)

"""Ahora vamos a utilizar la función apply para mostrar la forma de aplicar múltiples veces la misma función dentro de una base de datos, en este caso el CV para todas las columnas de la base de datos:"""

apply(telco,2,CV)

"""La variable bill es efectivamente la de mayor variación alrededor de su media, mientras los minutos gastados son bastante menos variables. En constraste, la relativamente baja variabilidad de los minutos (minutes) puede permitir una mejor planeación de los recursos operativos para satisfacer la demanda que se enfrenta. Ahora, por qué si el consumo de minutos es poco variable, la factura si lo es? Una posible especulación gira alrededor de los servicios adicionales (internet, juegos, etc…)

El 2 dentro de la función apply implica que se hace la función para todas las columnas; si se usara 1 funcionaría para todas las filas.

Ahora vamos a mostrar un paquete(librería) que hace múltiples descriptivos para un dataframe.
Dado el volumen de información que algunas salidas de R producen, puede ser interesante guardarlas en un dataframe.
"""

describe(telco)
telcostat<-describe(telco)
str(telco)

"""AL observar los resultados, llama la atención la alta tendencia central de score. Ese es un indicador de alerta para el negocio. Su asimetría positiva indica que probablemente hay más scores altos de lo esperado (o que hay scores muy altos, pero dado que hay un límite máximo al valor de scores, está no es probablemente la interpretación). Así mismo tenemos para *bill*, altas curtosis (signo de atípicos) y alta asimetría positiva, que contrasta con la baja asimetría y curtosis de minutos.
Vamos a adicionar el CV a esta base de datos y luego calcular un estadístico a lo largo de las variables , en este caso, la media geométrica de los CVs.
"""

cvs<-apply(telco,2,CV)
telcostat2<-cbind(telcostat,cvs)
geometric.mean(telcostat2$cvs)
telcostat2

"""

Para obtener medidas de posición puede ser importante pasar un vector que diga cuáles cuantiles queremos"""

quantile(bill)

quantile(bill, c(.10,.45,.90))

cuantiles<-apply(telco,2,quantile)
cuantiles

"""Si bien el 90% de los clientes tienen facturas de 582.7 dólares o menos, el máximo es de más del doble (1667 dpolares)

###Gráficos univariados

Ahora vamos a ver unos gráficos univariados básicos:
"""

hist(bill)

boxplot(bill)

qqnorm(minutes)

"""Son claramente observables: la asimetría positiva de bill (valores largos y más frecuentes de lo esperado en la cola) y su existencia de atípicos y una interesante cercanía a la curva normal del consumo en minutos.

Por supuesto los datos de los gráficos también se pueden guardar. Miremos su estructura.
"""

boxguarda<-boxplot(bill)
str(boxguarda)

"""En un diagrama de caja y bigotes hay diferentes informaciones para guardar: los cuantiles, la cantidad de datos, y los atípicos. Esta infromación puede ser de diferentes longitudes o inclusive de diferente tipo de variables. Por eso se almacenan en una lista, que es en sí misma una colección de objetos diferentes (por ejemplo, vectores y matrices de diferentes dimensiones). Si solo quiero los atípicos, basta con llamarlos:"""

boxguarda$out

"""###Descriptivos de variables categóricas

Para las variables categóricas usualmente se manejan tablas y gráficos de barras.
"""

table(cartera$tipoips)

"""Para graficarlo, se guarda la tabla y se grafica:"""

tabla1<-table(cartera$tipoips)
barplot(tabla1, main="Cantidad de IPS", xlab="Tipo de IPS")

"""Con la tabla se pueden realizar algunos cálculos de frecuencias adicionales:"""

prop.table(tabla1)

"""Esta variable marca la complejidad (tamaño) de la IPS en valores de 1 a 6. Tenemos algunos datos perdidos, y en general se presenta una estructura esperada: más clientes pequeños (de baja complejidad) y unos pocos clientes grandes.
Una medida interesante para una variable categórica es su entropia, que puede indicar qué tanta dispersión/uniformidad hay entre las categorías. Veamos:



"""

install.packages("infotheo")
library(infotheo)
cartera$tipoips<-as.factor(cartera$tipoips)
entropy(cartera$tipoips)

"""La entropía directa es interpretable en términos de transmisión de información (i.e, bits o nats necesarios para comunicar la variable). Unas medidas más fácilmente interpretables serían la entropía relativa a su máximo y el número efectivo de especies (que puede leerse como el número de categorías que debiéramos tener y puede guiar la agrupación de categorías)"""

##para que funcione la ecuación se debe trabajar con factores
entropia_relativa<-entropy(cartera$tipoips)/log(nlevels(cartera$tipoips))
especies<-exp(entropy(cartera$tipoips))
entropia_relativa
especies

"""Esto indicaría que la entropía actual es un 70% de la entropía máxima (uniformidad) y que el número efectivo de categorías es inferior a las 5 actuales (un poco más de 3)

###Cruces básicos de variables
Para cruzar dos variables escalares, basta con usar plot con las dos variables. En este caso, al tener dos variables escalares, tendríamos un gráfico de dispersión.

"""

plot(minutes, bill)

"""La medida descriptiva adecuada para comparar dos variables escalares (desde el punto de vista lineal) es la correlación"""

cor(minutes, bill)

"""En este caso, queda aún más patente que los aumentos en la factura no se deben a los minutos. El consumo telefónico es solo un gancho para atraer a los clientes a productos más rentables.

Para cruzar una variable categórica con una escalar, se usa un diagrama de caja y bigotes dividido y descriptivos divididos:
"""

boxplot(MESES~retrasos, data=cartera)
tapply(cartera$MESES, cartera$retrasos, mean)
tapply(cartera$MESES, cartera$retrasos, sd)

"""Al parecer, los clientes sin retrasos tienden a llevar más meses como clientes de la empresa. Para cruzar dos variables categóricas, lo usual es una tabla cruzada:"""

table(cartera$tipoips, cartera$retrasos)

"""Con ciertas librerías es posible obtener algunas tablas más completas"""

attach(cartera)
install.packages("gmodels")
library("gmodels")
CrossTable(tipoips, retrasos)

"""Y finalmente un gráfico con residuales de pearson:"""

install.packages("vcd")
library("vcd")
mosaic(~tipoips + retrasos,data=cartera,
       legend=TRUE, shade=TRUE)

"""No parece haber una relación entre el tamaño/complejidad de la IPS y si se retrasa o no. Veamos el estadístico básico adecuado, que nos indica que el resultado está muy cerca a los límites clásicos de la significancia:





"""

chisq.test(tipoips,retrasos)

"""En este ejemplo hemos hecho un repaso rápido de mecanismos descriptivos univariados y bivariados dependiendo del tipo de variable, y revisado algunas interpretaciones iniciales. Al final del mismo es importante reforzar los conceptos practicando con nuevas bases de datos o profundizando más en las aquí cargadas.
Para tener un mayor control y estética en los gráficos se sugiere trabajar con la información (notebooks de visualización)

##Librerías de resumen
En el siguiente apartado mostraremos algunas librerías de resumen que ayudan a visualizar rápidamente resultados descriptivos. Primero, para las variables escalares:
"""

library(summarytools)
describe_total<-descr(cartera)
describe_total

"""Luego para las categóricas"""

freq(cartera,plain.ascii = FALSE, style = "rmarkdown")

view(dfSummary(cartera))

"""Histogramas para todas las variables escalares"""

library(DataExplorer)
plot_histogram(cartera)

#Y luego para todas las variables categóricas, un gráfico de barras.

plot_bar(cartera)

"""¿Qué dificultas surge si se desea un boxplot en un único gráfico para todas las variables escalares?

Ahora crucemos variables escalares (e incluyamos la descripitiva univariada)
"""

library(GGally)
ggpairs(cartera[,-9])+ theme_bw()

"""Crucemos todas, y demos color por una variable categórica (aquí estamos agregando los cruces categórico/escalares)"""

ggpairs(cartera, aes(color=retrasos))+ theme_bw()

"""Otra opción de cruces categórico-escalares"""

plot_boxplot(cartera, by = "retrasos")

#Los cruces categórico / categórico

cartera$tipoips<-as.factor(cartera$tipoips)
ctable(x=cartera$tipoips,y=cartera$retrasos,digits=2,chisq=TRUE)

plot_bar(cartera,with="retrasos")
##alternativa para alinearlos a un 100% by="retrasos"

install.packages("ggmosaic")

library(ggmosaic)
ggplot(data=cartera)+geom_mosaic(aes(x=product(tipoips,retrasos),fill=retrasos))
