# -*- coding: utf-8 -*-
"""KNN_current.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjCMkpm4GHJMg9qKPjZ_Jjr_huSsqhK7

# **Un modelos básico de clasificación: KNN**

El objetivo de este libro de notas es presentar la técnica de K vecinos más cercanos como alternativa al problema de clasificación.
"""

if (!require('readxl')) install.packages('readxl')
if (!require('caret')) install.packages('caret')
if (!require('MLmetrics')) install.packages('MLmetrics')
if (!require('e1071')) install.packages('e1071')

"""## **KNN**

#Data and business understanding
"""

library(readxl)
library(caret)
library(MLmetrics)
library(ROCR)
library(e1071)

"""Trabajaremos con el contexto del archivo de cartera de empresas. Para mantener los libros de nota modulares, repetiré aquí el contexto:"""

cartera<-read_excel("carteraguia2017.xlsx")

str(cartera)

"""El archivo contiene datos de clientes de un proveedor de instituciones de salud (IPS), la cartera que presentan y si se han retrasado o no. Se trata entonces de un negocio B2B en el sector de la salud que desea predecir o averiguar indicadores de posibles aumentos y retrasos en su cartera

Entre las variables predictoras se incluyen:

MESES: Los meses que la empresa lleva siendo clientes del proveedor.

Tipo_IPS: De 1 a5, el nivel de complejidad de la institución de salud cliente (1=bajo, 5=alto)

IGUAL_DUEÑO: Número de años en que la IPS ha tenido el mismo dueño.

AGNOS_DIRECCION_ACTUAL: Número de años en que la IPS ha estado en la misma dirección.

VENTAS_MENS_PROMEDIO: Valor de ventas mensuales promedio de la IPS en millones de pesos.

PORC_PASIVOS_VENTA_ANUAL: Porcentaje de pasivos/ venta anual del último balance disponible.

CARTERA_ACTUAL_INSUMOS_A: Valor de la deuda con el proveedor en insumos de alta rotación (gasa, jeringas, por ejemplo) en millones de pesos.

CARTERA_ACTUAL_INSUMOS_B: Valor de la deuda con el proveedor en insumos de baja rotación (equipos, instrumentos, por ejemplo) en millones de pesos.

La variable a predecir son los RETRASOS, que indican sí el cliente se ha retrasado o no, siendo 1=sí y 0=No.

# Data preparation

Primero vamos a convertir a factores las dos variables que lo requieren: Tipo IPS y Retrasos y reordenamos la base de datos para dejar los predictores escalares juntos
"""

cartera$TIPOips<-as.factor(cartera$TIPO_ips)
cartera$retrasos<-as.factor(cartera$retrasos)
carterafin2<-cartera[,c(1,3,4,5,6,7,8,2,9)]

str(carterafin2)

"""Dado que la técnica de k vecinos más cercanos se basa en la idea de encontrar los k vecinos más cercanos de un caso a clasificar, es necesario definir una métrica de distancia entre casos, y calcular dicha distancia, por lo que aplican todas las recomendaciones trabajadas en clustering. En particular, en este caso, vamos a estandarizar la base de datos para evitar los efectos debido a la diversidad de unidades."""

# estandarización de las variables escalares
carterafin2[1:7]<-scale(carterafin2[1:7])

"""Por último, creemos bases de entrenamiento y validación"""

set.seed(1545867)
#aquí se define el tamaño de la muestra, en este caso entrenamiento tendrá el 75% de los casos
sample <- sample.int(nrow(carterafin2), floor(.75*nrow(carterafin2)))
cartera.train <- carterafin2[sample, ]
cartera.test <- carterafin2[-sample, ]

"""# Modelling

Para crear el modelo de k vecinos más cercanos es necesario tomar un caso de la base de datos de prueba y calcular sus k vecinos más cercanos de la base de datos de entrenamiento. La categoría a la que pertenezcan la mayoría de estos k vecinos más cercanos en la base de entrenamiento será la categoría asignadad al caso en la base de datos de prueba.

Para encontrar los k vecinos más cercanos más cercanos se usa una métrica de distancia, que por defecto es la distancia euclídea.

La selección del valor de k es importante, puesto que a menor k, mayor posibilidad de ruido en la clasificación, pero a mayor k, más cercano el resultado a un modelo ingenuo (promedio).

Por ello k se configura como un hiperaparámetro, que puede ser sintonizado con ayuda de la validación cruzada en la base de datos de entrenamiento, como se ve a continuación.
"""

# creo parámetros de validación cruzada
cross<-trainControl(method="cv",number=10)
modeloknn1<-train(retrasos~.,method="knn",
                  tuneGrid=expand.grid(k=1:30),
                  trControl=cross,
                  metric="Accuracy",
                  data=cartera.train)

modeloknn1
plot(modeloknn1)

"""De los resultados obtenidos es visible que el modelo más parsimonioso con buenos resultados usa k=6, y el modelo seleccionado por el método es de k=11. Vamos a hacer predicciones basados en la sugerencia del modelo."""

predmod1<-predict(modeloknn1,cartera.test,type="prob")
colnames(predmod1)<-c("no","si")
pronknn1<-ifelse(predmod1$si > 0.5,1,0)
confknn1<-confusionMatrix(as.factor(pronknn1),
                          cartera.test$retrasos, positive = "1")
confknn1$table
as.data.frame(confknn1$byClass)

"""Ahora veamos la curva COR"""

library(ROCR)
#crear objeto de predicciones
pr<-prediction(predmod1$si,cartera.test$retrasos)
#creacion del objeto de la curva
curvaROC<-performance(pr,measure="tpr",x.measure="fpr")
#grafico de la curva
plot(curvaROC)
plot(curvaROC, colorize=TRUE, colorkey=TRUE, print.cutoffs.at=c(0.35))

#calcular el AUC
auc<-performance(pr,measure = "auc")
auc <- auc@y.values[[1]]
#ver el AUC
auc

"""Podemos ver que los resultados son competitivos con la regresión logística (hecha en un notebook previo) donde sin balancear, el AUC obtenido era apenas 1.2 puntos porcentuales superior

Sin embargo nótese que estamos usando como medida de precisión “accuracy”. Dado el ligero desbalance de la base de datos, y que nos interesa particularmente predecir los retrasos, quizás sea mejor utilizar otra métrica y balancear.


"""

if (!require('ROSE')) install.packages('ROSE')
library(ROSE)

cartera.train.over<-ovun.sample(retrasos~.,data=cartera.train,method="over",p=0.49,seed=398)$data
table(cartera.train.over$retrasos)

"""Debemos hacer algunos ajustes para que la librería caret me permita usar el AUC"""

##para hacerlo con AUC
levels(cartera.train.over$retrasos) <- make.names(levels(factor(cartera.train.over$retrasos)))

# creo parámetros de validación cruzada
cross<-trainControl(method="cv",number=5,
                    classProbs = TRUE,
                    summaryFunction =prSummary)
modeloknn2<-train(retrasos~.,method="knn",
                  tuneGrid=expand.grid(k=1:30),
                  trControl=cross,
                  metric="AUC",
                  data=cartera.train.over)
modeloknn2
plot(modeloknn2)

"""El modelo me pide un número alto de vecinos. Veamos su desempeño en prueba"""

# el modelo sintonizado
predmod2<-predict(modeloknn2,cartera.test,type="prob")
pronknn2<-ifelse(predmod2$X1 > 0.5,1,0)
confknn2<-confusionMatrix(as.factor(pronknn2),
                          cartera.test$retrasos, positive = "1")
confknn2$table
as.data.frame(confknn2$byClass)

"""El modelo mejora en F score. Veamos su métrica AUC"""

#crear objeto de predicciones
pr2<-prediction(predmod2$X1,cartera.test$retrasos)
#creacion del objeto de la curva
curvaROC2<-performance(pr2,measure="tpr",x.measure="fpr")

##
#grafico de la curva
plot(curvaROC2)
plot(curvaROC2, colorize=TRUE, colorkey=TRUE)

#calcular el AUC
auc2<-performance(pr2,measure = "auc")
auc2 <- auc2@y.values[[1]]
#ver el AUC
auc
auc2

"""Los resultados son inferiores a los de una regresión logística con selección de variables basada en pasos sucesivos y balanceo, pero no por mucho.

Aunque KNN también puede usarse para predicciones de variables escalares, KNN es con frecuencia un modelo que puede utilizarse como modelo de base o ingenuo para una clasificación, particularmente con variables predictoras escalares.
También podemos comparar gráficamente los dos modelos que hemos hecho con KNN
"""

plot(curvaROC, col="#2c5697")
plot(curvaROC2, col="#d20728", add=TRUE)

"""Obsérvese que nuestro modelo balanceado obtuvo el máximo k posible. ¿aumentar el k mejorará aun más los resultados? Miremos"""

modeloknn3<-train(retrasos~.,method="knn",
                  tuneGrid=expand.grid(k=31:70),
                  trControl=cross,
                  metric="AUC",
                  data=cartera.train.over)

modeloknn3$bestTune

resamps <- resamples(list(con_30 = modeloknn2, con_63 = modeloknn3))
xyplot(resamps, what = "BlandAltman")

"""Parece que en cada submuestra el modelo de 65 se desempeñó mejor que el de 30. Es posible hacer una diferencia t de student de muestras pareadas dado que los remuestreos son iguales. El resultado en entrenamiento es que hay un posible aumento en el AUC"""

diffs <- diff(resamps)
summary(diffs)

"""Probémoslo en la base de prueba"""

predmod3<-predict(modeloknn3,cartera.test,type="prob")
pr3<-prediction(predmod3$X1,cartera.test$retrasos)
curvaROC3<-performance(pr3,measure="tpr",x.measure="fpr")

#calcular el AUC
auc3<-performance(pr3,measure = "auc")
auc3 <- auc3@y.values[[1]]
#ver el AUC
auc2
auc3

"""En la base de prueba, el aumento de k muestra de hecho un decrecimiento, debido a un posible underfitting. Sería importante analizar si bajar el k (inclusive por debajo de 30) mantiene o mejora el desempeño.

##Conclusión
En este libro de notas revisamos la técnica de KNN para clasificación, que puede usarse como línea de base ingenua y que es sorprendentemente bueno a pesar de su sencillez. Un modelo más sofisticado debe demostrar su utilidad frente a modelos ingenuos para justificar el esfuerzo de su realización. lastimosamente, esta técnica básica no es muy escalable a grandes volúmenes de datos.
"""