# -*- coding: utf-8 -*-
"""Naive_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUbpPmg28lBPfLRxzIc6C7vDfl5mk4l7

# ** Bayes ingenuo**

El objetivo de este libro de notas es presentar la técnica de Naive Bayes como alternativa al problema de clasificación.
"""

if (!require('readxl')) install.packages('readxl')
if (!require('caret')) install.packages('caret')
if (!require('MLmetrics')) install.packages('MLmetrics')
if (!require('e1071')) install.packages('e1071')

"""# ***  Naive Bayes (Bayes ingenuo) ***

Un modelo de clasificación que puede servir como pronóstico base o ingenuo, es conocido como Naive Bayes o Bayes ingenuo.

El resultado se basa en una relajación del Teorema de Bayes en la que la suposición principal es que las variables predictoras son independientes. Aunque es una suposición fuerte, en muchas ocasiones los resultados de Naive Bayes son bastante competitivos, y serán mucho mejores en la medida en que la suposición se cumpla.

# Data and business understanding

Los datos corresponden a una encuesta a 880 personas con respecto a su preferencia entre 3 opciones al desayuno: Avena, Barrita de desayuno o cereal. El objetivo es poder predecir una preferencia de acuerdo a información demográfica disponible que permitiera realizar promociones específicas.
"""

library(readxl)
library(caret)
library(MLmetrics)
library(ROCR)
library(e1071)

cereal<-read.csv("cereal2.csv", header=TRUE, sep=";", dec=",")
str(cereal)

"""Los predictores son:

Edadcat: La edad en categorías de edad.

Genero: El género del encuestado

ecivil: el estado civil

activo: Si la persona es o no activo en su vida diaria (sedentario o no)

Vamos a hacer un pequeño arreglo con el nombre de la edad categorizada y separar en bases de entrenamiento y validación en una partición 50%-50%
"""

#un pequeño arreglo
colnames(cereal)[1]<-"edadcat"

#genero entrenamiento y validacion para cereal
set.seed(19854)
sample <- sample.int(nrow(cereal), floor(.7*nrow(cereal)))
cereal.train <- cereal[sample, ]
cereal.test <- cereal[-sample, ]

"""# Modelling

La creación del modelo de Naive Bayes es relativamente simple, pues no existen hiperparámetros por sintonizar o parámetros a entrenar. Se trata simplemente de calcular las probabilidades de la categoría a predecir a partir de las categorías de las predictoras, suponiendo independencia entre ellas usando el Teorema de Bayes.
"""

naivetest<-naiveBayes(cereal.train$desayuno~.,cereal.train)

"""Un resultado a observar son las probabilidades a priori, que corresponden simplemente a las tasas base de las categorías a predecir. El segundo resultado a observar son las probabilidades marginales del predictor dada la categoría a predecir."""

#tasas base
naivetest$apriori

#probabilidades marginales
naivetest$tables$genero

naivetest$tables$edadcat

naivetest$tables$ecivil

naivetest$tables$activo

"""La primera tabla nos permite ver una base de datos bastante balanceada. Las siguientes tablas permiten ver qué característica individual parece discriminar mejor el desayuno elegido.


Por ejemplo, dado que se consume barrita de desayuno hay una mayor probabilidad de que sea mujer, o dado que se consume avena hay una buena probabilidad de que se trate de una persona de más de 42 años, particularmente los mayores de 60.

## Evaluation

Creamos el objeto de predicción que nos permite ver el desempeño en la base de datos de validación
"""

#guarda las probabilidades (para curva COR)
prednaiveprob<-predict(naivetest, cereal.test, type="raw")

#guarda el pronóstico
prednaive<-predict(naivetest, cereal.test)

str(prednaive)

#generar la matriz de confusión
naiveconf<-confusionMatrix(prednaive,as.factor(cereal.test$desayuno))
naiveconf$table

as.data.frame(naiveconf$byClass)

"""Nótese que la predicción requiere de 3 clases diferentes. Es por ello que la matriz de confusión presenta los indicadores divididos por cada uno de los tres valores, para saber qué tan buena es la predicción para cada posible desayuno. Si se hubiese definido el desayuno a predecir, los resultados hubiesen salido solo para ese tipo de desayuno.

Como puede analizarse, la avena es la más fácil de predecir (F=65%, precisión 59% y exhaustividad 74%). Para las otras dos clases, los F scores son menores al 50%.

Cuando se tiene un problema multiclase, se suelen obtener tendencias centrales del F score para todas las clases, conocidas como F micro y F macro. La F macro es una media ponderada de los F score de cada categoría; la F micro es el mismo *accuracy*, es decir, el total de éxitos sobre el total de la base.  


"""

##calcular macro y micro F1
guarda<-naiveconf$table
guarda2<-as.data.frame(naiveconf$byClass)
guarda2$n<-naivetest$apriori
##Macro F1
macrof1<-mean(guarda2$F1)
##Weighted F1
macrof1_weighted<-weighted.mean(guarda2$F1,guarda2$n)
##micro f1= accuracy
microf1<-(guarda[1,1]+guarda[2,2]+guarda[3,3])/(sum(guarda))
macrof1
macrof1_weighted
microf1

"""
Los siguientes son los pasos para obtener una curva COR para la avena."""

#crear resultados 1 o 0 para la predicción de Avena
avenas<-ifelse(cereal.test$desayuno=="Avena",1,0)

#crear el objeto de prediccion
predcor<-prediction(prednaiveprob[,1], avenas)

curvaROC<-performance(predcor,measure="tpr",x.measure="fpr")

#grafico de la curva
plot(curvaROC, colorize=TRUE,colorkey=TRUE)

#calcular el AUC
auc<-performance(predcor,measure = "auc")
auc <- auc@y.values[[1]]
#ver el AUC
auc

"""El resultado para avena es bueno. Sin embargo miremos el resultado para cereal."""

#crear resultados 1 o 0 para la predicción de cereal
cerealk<-ifelse(cereal.test$desayuno=="Cereales",1,0)

#crear el objeto de prediccion
predcor2<-prediction(prednaiveprob[,3], cerealk)

curvaROC2<-performance(predcor2,measure="tpr",x.measure="fpr")

#grafico de la curva
plot(curvaROC2,colorize=TRUE,colorkey=TRUE)

#calcular el AUC
auc2<-performance(predcor2,measure = "auc")
auc2<- auc2@y.values[[1]]

#ver el AUC
auc2

"""El resultado para cereal es de tan solo 62.2%, por lo que Naive Bayes no es muy satisfactorio para predecir esta categoría.

Aquí también podemos generar todos los puntos de corte, y calcular ganancias.
"""

#guardar las exhaustividades y puntos de corte
tablafinan<-performance(predcor2,measure="rec")
cutoffs<-unlist(tablafinan@x.values)
recalls<-unlist(tablafinan@y.values)

#guardar las precisiones
tablafina2<-performance(predcor2,measure="prec")
precisions<-unlist(tablafina2@y.values)

#guardar f scores
tablafina3<-performance(predcor2,measure="f")
fscores<-unlist(tablafina3@y.values)

#crear la tabla conjunta
tablacruce<-as.data.frame(cbind(cutoffs,precisions,recalls,fscores))

#ver precisiones versus exhaustividad
plot(tablacruce$precisions,tablacruce$recalls)

#ver el cutoff que maximiza f score
ggplot(tablacruce, aes(cutoffs,fscores))+geom_point()

#calcular las ganancias
tabla<-table(cereal.test$desayuno)
prop.table(tabla)[3]
tablacruce$wins<-prop.table(tabla)[3]*recalls*(250-(100/precisions))

#pintar las ganancias versus los cutoffs
plot(tablacruce$cutoffs,tablacruce$wins)

#ver las ganancias frente a la precisi?n
plot(tablacruce$precisions,tablacruce$wins)

"""## Conclusión

En este libro de notas revisamos la técnica de bayes ingenuo para de clasificación, que puede usarse como línea de base ingenua y que es sorprendentemente buena a pesar de su sencillez. Un modelo más sofisticado debe demostrar su utilidad frente a modelos ingenuos para justificar el esfuerzo de su realización. Así mismos esta técnica básica suelen ser altamente escalables a grandes volúmenes de datos.
"""