# -*- coding: utf-8 -*-
"""SVD_factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9NV7LMYDzPXnP21QEtHiTsbjapgq59b

##Componentes principales

El objetivo del Notebook es ejemplificar el uso e interpretación de componentes principales como técnica de reducción de dimensionalidad.

Componentes principales nos permite entender la estructura de los datos y saber si es posible hacer una reducción de dimensiones a partir de una factorización de la matriz de covarianzas (correlaciones) de los datos.

Componentes principales está basado en la técnica de descomposición de matrices llamada singular value decomposition (SVD).

El libro contiene un ejemplo relacionado con scoring y otro con investigación de mercados.
Instalemos librerías:
"""

install.packages(c("corrplot","psych","FactoMineR","factoextra","reshape2","RColorBrewer"))

"""#Ejercicio 1
##Data understanding & preparation

Primero importemos la base de datos
"""

cartera<-read.csv("cartera.csv", header=TRUE, sep=";", dec=",")
str(cartera)

"""El archivo contiene datos de clientes de un proveedor de instituciones de salud (IPS), la cartera que presentan y si se han retrasado o no. Se trata entonces de un negocio B2B en el sector de la salud que desea predecir o averiguar indicadores de posibles aumentos y retrasos en su cartera.

En nuestro caso el tipo de Ips es una variable categórica y debe ser removida (variable # 2). Como nuestro objetivo es ver la estructura de los datos escalares antes de predecir si la IPS se retrasa o no también vamos a eliminar la variable retrasos (variable #9)
"""

quita<-c(2,9)
carteraz<-cartera[,-quita]

"""Para que la solución de componentes principales logre su objetivo de reducción de variables es importante que haya correlaciones entre las variables; de otro modo, la reducción no será posible. Exploremos gráficamente si ello es viable."""

library("corrplot")
#creo matriz de correlaciones
base<-cor(carteraz)
#ejecuto el gráfico
corrplot(base, type="upper",method="square",title="Matriz de correlaciones", tl.cex=0.6,order="hclust", addCoef.col = "black", number.cex=0.5)

"""El gráfico muestra una moderada correlación positiva entre algunas variables, por lo que alguna reducción puede ser viable.

Un paso final de la preparación es estandarizar las variables para evitar problemas relacionados con las diferentes dimensiones en las que vienen dichas variables. Sin embargo, ese paso se hará en la modelación explicada a continuación.

##Modeling

Con la siguiente instrucción aplicamos componentes principales. Observe que estandarizamos las variables con las instrucciones center (restamos la media) y scale (dividimos por la desviación)
"""

componentestotal<-prcomp(carteraz, center=TRUE, scale.=TRUE)
summary(componentestotal)

"""La solución presenta 7 componentes principales para las 7 variables, en los que se ha logrado una factorización en componentes de forma tal que están ordenados de mayor a menor capacidad de explicación de la variabilidad de los datos. Explicando en detalle, la primera fila corresponde a las desviaciones estándar capturadas por cada uno de los 7 componentes. Estas desviaciones estándar son las raíces cuadradas de los denominados eigenvalues. Los eigenvalues se pueden explicar como la cantidad de variabilidad explicada por el componente expresada en número de variables. Así, si el primer componente tiene desviación de 1.8 su eigenvalue es 1.8x1.8=3.254, lo que significa que el primer componente captura la variabilidad equivalente a 3.2 variables. Nótese que a partir del tercer componente, la variabilidad capturada es inferior a la de una variable. La suma de los eigenvalues debe ser equivalente al número de variables (en este caso, 7). La segunda fila (Proportion of variance) facilita la interpretación anterior al mostrar el porcentaje de varianza explicado por el componente. Por ejemplo, 3.254 variables corresponden al 46.49% de 7 variables. La tercera fila muestra ese porcentaje de forma acumulada.

Por supuesto, la siguiente pregunta se refiere a cuántos componentes principales tomar para hacer la reducción. Para ello miremos el gráfico de sedimentación (screeplot):
"""

plot(componentestotal, type="l")

"""Por tratarse de un método no supervisado no existe un criterio establecido para definir cuántos componentes principales usar como reducción de las variables originales. Las opciones son:

    Elegido por dominio (a priori): El problema de negocio da pistas sobre cuántos componentes se requiere o es viable trabajar.
    Uso de eigenvalues: usar componentes que expliquen más de una variable, o sea, de autovalor (eigenvalue) superior a 1.
    Determinar un porcentaje de la varianza a alcanzar. La ley de los pocos vitales usa el 80% de proporción acumulada como valor empírico de corte.
    Gráfico de sedimentación: revisar en dónde el gráfico de sedimentación genera un "codo" o cambio de pendiente.

El criterio B implicaría el uso de 2 componentes; el criterio C manejaría 3. El gráfico de sedimentación ubica el valor aproximadamente entre 2 o 3 componentes. En este caso vamos a utilizar 2 componentes principales (69.7% de la variabilidad) pues va a facilitar el análisis.
"""

componentes<-prcomp(carteraz, center=TRUE, scale.=TRUE, rank.=2)
print(componentes)

"""La tabla mostrada presenta los valores estandarizados del vector del componente seleccionado, llamados autovectores. A partir de ellos se calcularía la puntuación factorial para cada IPS.
Evaluation

Para interpretar los autovectores, lo usual es mirar qué variables tienen valores altos en el vector. Esas serán las variables mejor representadas en el mismo. Para ello haremos un gráfico:
"""

library(reshape2)
library(ggplot2)
cargas<-componentes$rotation
cargasdf<-as.data.frame(cargas)
cargasdf$medicion<-rownames(cargasdf)
cargasheat<-reshape2::melt(cargasdf)
colnames(cargasheat)<-c("variable","componente","carga")
library(ggplot2)
ggplot(cargasheat,aes(x=componente,y=variable,fill=carga, label=sprintf("%0.2f", round(carga, digits=2))))+geom_tile()+scale_fill_distiller(palette="RdBu")+geom_text()

"""Por ejemplo, aunque el primer componente tiene valores similares en todas las variables, las 4 más altas en valor absoluto (por encima de 0.4) son las carteras A y B, las ventas promedio y el tiempo con el mismo dueño. En el segundo componente la variable que puntúa más alto es el pasivo sobre venta. El componente 2 muestra que a mayores pasivos sobre venta tiende a tener la IPS, menores años en la dirección actual tiende a tener. De nuevo, cuántas variables ayudan a explicar o representar el componente es un asunto de juicio. La regla empírica que utilizo es tantas como la variabilidad representada por el autovalor. En este caso, el primer componente tendría casi 4 y el segundo entre 1 y 2.
Al realizar interpretaciones de dichos autovectores como factores latentes, entramos en el campo del análisis factorial. Por ejemplo, si digo que el primer componente representa la pequeñez e inestabilidad de la empresa, y el segundo su nivel de endeudamiento, estoy asignando interpretaciones como factores latentes a los autovectores que pueden ayudarme posteriormente a interpretar mi modelo. Para este caso, si quiero mejorar la interpretación puedo recurrir a una rotación:
"""

library(psych)
componentes2<-principal(carteraz,nfactors=2,rotate="varimax")
# rotaciones disponibles: "none", "varimax", "quatimax", "promax", "oblimin", "simplimax", and "cluster"
as.data.frame(componentes2$communality)
componentes2$loadings

"""Las comunalidades permiten ver la cantidad o porcentaje de la varianza de cada variable que la solución factorial representa. La variable mejor representada es la cartera B, mientras que la menor representada es la de años en la dirección actual.

Grafiquemos las puntuaciones:
"""

componente1<-componentes2$loadings[,1]
componente2<-componentes2$loadings[,2]

cargasdfr<-as.data.frame(cbind(componente1,componente2))
cargasdfr$medicion<-rownames(cargasdfr)
cargasheatr<-reshape2::melt(cargasdfr)
colnames(cargasheatr)<-c("variable","componente","carga")
ggplot(cargasheatr,aes(x=componente,y=variable,fill=carga, label=sprintf("%0.2f", round(carga, digits=2))))+geom_tile()+scale_fill_distiller(palette="RdBu")+geom_text()

"""Si bien la solución factorial no cambia pues la interpretación varía un poco. Ahora es más claro que el componente 1 representa una antigüedad con algo de tamaño (meses de cliente, años en la dirección actual y con el mismo dueño) mientras que el componente 2 representa la deuda.

Una vez tenemos la interpretación, y si nos satisface la reducción obtenida, podemos guardar las puntuaciones factoriales en la base de datos:
"""

#guardo las puntuaciones factoriales- ojo son las de la primera solución
pc<-componentes$x
#uno las dos columnas a la base inicial
carterapc<-cbind(cartera,pc)
carterapc$retrasos<-as.factor(carterapc$retrasos)
#dos gráficos
plot(carterapc$PC1,carterapc$PC2)

ggplot(carterapc,aes(x=PC1,y=PC2,color=retrasos))+geom_point()

"""Obsérvese que guardamos la solución no rotada para la interpretación. Cuando el componente 1 (pequeñez) es bajo, el componente 2 (deuda) separa los retrasos. La interpretación es que en las empresas grandes, el tamaño de la deuda permitirá prever si habrá o no retrasos. La división es menos clara cuando el tamaño de la empresa es pequeño.

Hagámoslo con la solución rotada:
"""

#guardo las puntuaciones factoriales
pca<-componentes2$scores
#uno las dos columnas a la base inicial
carterapca<-cbind(cartera,pca)
carterapca$retrasos<-as.factor(carterapca$retrasos)

ggplot(carterapca,aes(x=RC1,y=RC2,color=retrasos))+geom_point()

"""Como análisis, Cuando el componente de antiguedad-tamaño es alto, la deuda me permite predecir si habrá o no retrasos.
##Ejercicio 2

Este ejercicio se basa en la evaluación sensorial de un producto nuevo de papas fritas sabor salmón.
"""

library(readxl)
fritasfp<-read_excel("fritas1.xlsx")
fritasf<-as.data.frame(fritasfp[,-1])
rownames(fritasf)<-fritasfp$Marca
str(fritasf)

"""En este ejercicio tenemos 23 marcas de papas fritas, y 38 evaluaciones (muchas de ellas sensoriales) de cada marca. Las últimas 4 variables representan respuestas deseadas de mercadeo (mayor pago, imaginarse comiendo, etc.). En este caso resulta de importancia la reducción de dimensiones dado el número de casos vs. variables; así mismo para detectar factores fundamentales en la evaluación de la papa frita. Revisemos las correlaciones y agreguemos a ellas un mapa de calor."""

corrmatrix<-cor(fritasf[,1:38])
corrplot (corrmatrix, tl.cex=0.5, type="upper")

#heatmap(corrmatrix)
#heatmap(corrmatrix, col=terrain.colors(12))
heatmap(corrmatrix, col=cm.colors(8))

"""El mapa de calor realiza un cluster jerárquico entre los vectores de correlación, poniendo entonces más cerca aquellas variables cuyas correlaciones con las demás variables se parecen más entre sí (lo cual puede ser una aproximación descriptiva a lo que ocurrirá al hacer la reducción de dimensiones).

Ahora usaremos las librerías FactoMineR y Factoextra para obtener los resultados del análisis factorial.
"""

library("FactoMineR")
library("factoextra")
library(reshape2)
library(RColorBrewer)

frifact<-PCA(fritasf,ncp=6,quanti.sup = c(39:42), graph=FALSE)
#gráfico de codo
fviz_eig(frifact,choice="eigenvalue",geom="line", title="gráfico de codo")

fviz_eig(frifact,choice="variance",geom=c("bar","line"), title="gráfico de codo")

componentes2<-prcomp(fritasf[,1:38],center=TRUE, scale.=TRUE)
summary(componentes2)

"""Con el criterio de eigenvalues, estaríamos hablando de 7 componentes principales, cubriendo el 87.5% de la variabilidad.

Los siguientes gráficos permiten visualizar las contribuciones de las variables a los autovalores, y de los casos también (en caso de que ello sea relevante, como en el ejemplo).
"""

fviz_contrib(frifact,choice="var", axes=1)

fviz_contrib(frifact,choice="ind")

"""

Si bien la línea roja busca dar una guía de hasta donde utilizar las variables o casos, no es un criterio definitivo, y el análisis debe ser descriptivo dentro del contexto del problema. Por ejemplo, este primer factor podría decirse que agrupa ciertos aspectos visuales (naranja, claro) con características deseadas como natural y premium. Es importante tener en cuenta que en este gráfico no se presenta el signo de la contribución, así que algunos de ellos podrían ser negativos y otros positivos.

Un gráfico más adecuado para esta interpretación se presenta aquí:"""

fviz_pca_var(frifact, geom =c("point","text"), repel=TRUE, labelsize=3)

"""En este caso sí es visible en qué dirección (de los ejes x e y) se dan las contribuciones; se muestran también las direcciones de las variables resultado. Podríamos definir por ejemplo un primer eje de los natural/sostenible/balanceado (que es naranja/rojo/claro) vs, lo complejo/global/procesado) que es más azul y negro. El segundo factor tendría un contraste entre el empaque plástico y lo ácido/picante vs. el empaque de papel (sabor dulce).

Podemos pedir otros ejes:
"""

fviz_pca_var(frifact,axes=c(3,4), geom =c("point","text"),repel=TRUE, labelsize=3)

"""

El factor 3 estaría conectado con lo urbano, moderno y de moda, mientras el factor 4 con lo simétrico, crocante, viejo y ácido (el cual es menos claro, al menos desde la percepción común)

Si se tiene una clasificación previa de variables (en este caso, sensorial) es posible indicarla en el gráfico, y de ese modo encontrar correspondencias entre sentidos y al interior de los sentidos."""

##adicional sobre los factores
###MFA (PCA with additional grouping variables)
frifact2<-MFA(fritasf,c(11,4,10,12,5),
              name.group=c("Visual","Tactil","Empaque/sabor","Conceptos","Premiumness"),ncp=6,num.group.sup = c(5), graph=FALSE)
fviz_mfa_var(frifact2,axes=c(1,2), geom =c("point","text"),repel = TRUE, labelsize=3)

fviz_mfa_var(frifact2,axes=c(3,4), geom =c("point","text"),repel = TRUE, labelsize=3)

"""Así mismo podemos ubicar las puntuaciones factoriales de los individuos para observar las cercanías entre ellos."""

fviz_pca_ind(frifact, ggtheme=theme_classic(), repel=TRUE, labelsize=3)

"""

Estos resultados invitan a realizar un clustering de individuos, que en este caso realizaríamos de modo jerárquico (pocos individuos) con distancia euclídea sobre las puntuaciones factoriales.

El código que se presenta a continuación, realiza un cluster jerárquico seleccionando de forma "automática" el número de clústeres y los gráfica"""

install.packages("plotly")
library(plotly)

friclust<-HCPC(frifact,nb.clust=-1)
res.hcpc<-friclust
grafico<-fviz_dend(friclust)
ggplotly(grafico)
fviz_cluster(res.hcpc, repel = TRUE, palette=c("red","blue","salmon"))