# -*- coding: utf-8 -*-
"""Recommender_Apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ch0LBXEb_JgJMB5QLZhAAOtbaYvFm2Ez

# **Sistemas de recomendación**

El objetivo de este Notebook es mostrar la manera de utilizar el algoritmo a priori para crear un sistema de recomendación en el caso de estudios de cosméticos presentado en la clase de Métodos y Aplicaciones de Analítica I

# ***Business understanding***

Utilizaremos para este ejemplo el contexto del archivo cosmeticspan.xlsx.

Se trata de una pequeña cadena de cosméticos con productos naturales/orgánicos que se ubica en paneles de 3x3 en grandes tiendas de departamentos y centros comerciales.

El análisis estratégico indicó que era importante buscar:

a) Productos bien vendidos juntos que pudiesen apalancar cross&up-selling por su ubicación en mostrador

b) Productos bien vendidos juntos candidatos a generar un producto innovador dadas las características del mercado

c) Productos premium asociados al labial que pudieran permitir una estrategia de precios

d) Llamar la atención sobre productos de baja venta mediante promociones con otros productos

e) Combinaciones de productos para los canales de redes sociales

#***Data preparation & understanding***
"""

library(readxl)
cosmetics3 <- read_excel("cosmeticspan.xlsx")

install.packages("arules")
install.packages("arulesViz")
install.packages("gmodels")
install.packages("vcd")
install.packages("igraph")
install.packages("factoextra")
install.packages("dendextend")
install.packages("grDevices")

library(cluster)
library(factoextra)
library(dendextend)
library(dplyr)
library(grDevices)

"""Como vemos, la tabla ya viene preparada como un conjunto de ceros y unos que indican la compra o no compra del producto por el cliente, y contiene 1.000 transacciones de clientes.

Para preparar los datos, dadas las posibles dificultades con datos dispersos, es necesario convertir la base de datos a una clase especial de R.

Cargaremos aquí entonces las librerías y haremos las conversiones, inicialmente a matriz y posteriormene al tipo de datos “transactions”
"""

#librerías necesarias
library(arules)
library(arulesViz)
#conversión a matriz
cosmetics4<-as.matrix(cosmetics3)
# convertir en transaction
cosmetics4<-as(cosmetics4,"transactions")

"""Como mirada descriptiva miremos el tamaño en ventas relativo de los diferentes productos:"""

itemFrequencyPlot(cosmetics4, topN=50,  cex.names=.5)

"""Esto nos permite ver que los dos productos menos vendidos son el lápiz de cejas y la cosmetiquera (para la estrategia D), mientras que los más populares son el lápiz y el brillo de labios.

# ***Modeling***

##Entendiendo support y lift del algoritmo apriori

Para entender mejor en qué consisten las asociaciones a priori, primero haremos una tabla de contingencia y un gráfico de mosaico
"""

#obtener una tabla de contingencia
library("gmodels")
crosst<-CrossTable(cosmetics3$Cosmetiquera, cosmetics3$Rubor, chisq = TRUE)

crosst

#graficar el resultado
library("vcd")
mosaic(~Cosmetiquera + Rubor ,data=cosmetics3,
       legend=TRUE, shade=TRUE)

"""Como podemos ver, una prueba de hipótesis cuya hipótesis nula es la asociación entre las dos variables obtiene un p-value pequeño, por lo que podemos considerar que hay una asociación en la compra de esos dos productos.

Miremos algunos detalles de lo que aquí se calcula para entender la asociación.
"""

##valores observados
crosst$chisq.corr$observed

crosst$prop.tbl

##valores esperados
crosst$chisq.corr$expected

"""Los valores observados (primera tabla) corresponden a lo que realmente ocurrió en las ventas: los productos rubor y cosmetiquera se vendieron 32 veces juntos. Ese valor observado como porcentaje del total corresponde a lo que se denomina support y se puede observar en la segunda tabla que es del 3,2%.

La tercera tabla muestra los valores esperados si los dos productos (o variables fuesen independientes). En este caso se esperaban sólo 19.6 ventas conjuntas, y en realidad ocurrieron 32. EL lift puede obtenerse dividiendo el valor observado sobre el esperado.
"""

lift<-32/19.6
lift

"""Este valor implica que los dos productos se vendieron juntos un 63,2% más de lo que se esperaría si fueran independientes en sus ventas.

El lift es una medida de negocio explicativa de lo que ocurre. Pero una medida estadística similar se puede obtener de una tabla chi-cuadrado: los residuales.
"""

##residuales
crosst$chisq.corr$residuals

##residuales ajustados
crosst$chisq.corr$stdres

"""En la primera tabla se obtienen los residuales Chi cuadrado que son una estandarización de los valores observados bajo el supuesto de que la media y la desviación estándar son los valores esperados (suposición Poisson). En ese caso lo que se ve es la posición relativa de los valores esperados en términos de desviaciones estándar (los productos de venden juntos 2.8 desviaciones estándar por encima de lo esperado)

La segunda tabla muestra esos residuales con una modificación importante que debe hacerse en tablas de 2x2. Diríamos entonces que los productos se venden 3.6 desviaciones por encima de lo esperado. Como este último si es un resultado estadístico, lleva como conclusión una prueba de hipótesis que indica que sí hay una asociación entre dichos productos.

Aqui la conversión a matriz:
"""

cosmetics4<-as.matrix(cosmetics3)

"""Y aquí la conversión a "transaction"
"""

cosmetics4<-as(cosmetics4,"transactions")

itemFrequencyPlot(cosmetics4, topN=50,  cex.names=.5)

"""##Aplicación del algoritmo a priori

Creemos el conjunto de reglas con el algoritmo a priori. Dado el gran volumen de reglas que puede crearse, es clave definir valores de corte de support, confidence o lift que permitan reducir el número de reglas. El support permite seleccionar ventas conjuntas que apliquen a un número mínimo de transacciones. El confidence es muy usado, ante todo, para evitar la duplicación de reglas, porque el support o el lift son iguales para la relación de los productos A y B, sin importar si la relación es (A entonces B) o (B entonces A). Eso hace que muchas reglas salgan repetidas, y el confidence puede ayudar a evitar que esto ocurra.
"""

rules<-apriori(cosmetics4,parameter=list(support=0.1,confidence=0.6))

"""Observemos algunas cosas básicas de las reglas: cuantas reglas hay con qué cantidad de productos, y observar las primeras reglas, por ejemplo"""

summary(rules)

inspect(head(sort(rules,by="lift"),20))

"""Podemos observar, por ejemplo, que el lápiz de labios si está incluido en alguna de las primeras 20 reglas. Así mismo, que hay muchas reglas que involucran 3 productos.


Podemos graficar las reglas por su lift y support

##Gráficos para ver potenciales asociaciones de interés
"""

plot(rules, measure=c("support","lift"), shading="confidence")

"""Claramente destacan una regla con alto lift (aunque el support no sea muy bueno) y 3 reglas con alto support (más del 30% de las transacciones)

Miremoslas interactivamente
"""

plot(rules, measure=c("support","lift"), shading="confidence", control=list(main="Reglas de MBA"))

"""Por ejemplo, si filtramos la zona de alto support con buen lift es visible una regla entre base y brillo de labios. Al tener soporte mayor al 30% y un lift mayor que 2 serán mis candidatas para poner en lugares extremos del mostrador (objetivo A)

Ahora daremos una mirada a las reglas que permita ver qué productos generan la mayor cantidad de reglas. Reduciré a confidence mayor a 0,7.
"""

inspect(head(sort(rules,by="support"),20))

subrules<-subset(rules,quality(rules)$confidence>0.7)
plot (subrules, method="matrix", measure="lift", control=list(reorder='support/confidence'))

"""Hay 6 productos que están presentes en todas las reglas, de los cuales 3 se llevan la mayoría. La máscarilla antiedad es una de las que mejor se lleva con otros productos, lo cual coincide con el análisis de industria. El corrector de ojeras o las sombras también tienen gran número de asociaciones.

Una alternativa más compleja pero que permite observar tanto lift como soporte es:
"""

plot (subrules, method="matrix", measure=c("lift", "support"), control=list(reorder='support/confidence'))

"""Así mismo, se pueden mirar las asociaciones como si fueran grafos:"""

subrules2 <- head(sort(rules, by="lift"), 10)
str(rules)

plot(subrules2, method="graph")

plot(subrules2, method="graph", arrowSize=.01)

"""Aquí por ejemplo resalta, además de la máscara y la sombra como elementos centrales en mi portafolio, la relación alta entre cepillos y esmalte.

A partir de la observación de las reglas y de la estrategia de negocios propongo:
a) Base y brillo de labios para la estrategia de ubicación en mostrador, de modo que la gente deba recorrer visualmente el mostrador para encontrar los dos productos. El alto soporte me garantiza muchas miradas
b) La combinación cepillos-esmalte, de altísimo lift y buen soporte para explorar la posibilidad de un producto innovador que pudiese duplicar la funcionalidad
c) Asociado al labial, donde la competencia es fuerte, están la mascarilla antiedad y las sombras. Como la mascarilla antiedad está en crecimiento y es altamente demandada de acuerdo al estudio de industria, se sugiere subir su precio y bajar el del labial para competir mejor, de modo que se mejoren las ganancias
e) Para el canal de redes sociales utilizar en una única promoción productos como el corrector de ojos y el delineador, relacionados con la misma parte de la cara y asociados en ventas
f) Resulta claro que la mascarilla antiedad y las sombras son productos centrales asociados a mi portafolio. Como la mascarilla la estoy usando en la estrategia C como un producto premium, propongo que la sombra se use cuando se requiera la creación de combos o promociones.

Obsérvese que no se planteó la estrategia D, porque ninguna regla se asocia a los productos de baja venta. Eso se debe a que utilizamos el support como criterio de disminución de reglas.

Por ello vamos a crear un nuevo set de reglas con menor soporte que me permita encontrar reglas para los productos de baja venta. Lo reducimos a máximo 3 productos, bajamos el soporte a 1% y las mostramos en orden ascendente:
"""

rules_lapiz<-subset(rules,subset=lhs %in% "Lapiz de labios")

inspect(head(sort(rules_lapiz,by="lift"),20))

rules2<-apriori(cosmetics4,parameter=list(support=0.01,confidence=0.7, maxlen=3))

inspect(head(sort(rules2,decreasing=FALSE, by="support"),20))

"""Puedo trabajarlo también como matriz de distancias"""

distancias<-dissimilarity(cosmetics4,method="jaccard",which="items")

fviz_dist(dist.obj=distancias)

cosmjer<-hclust(distancias)
plot(cosmjer, cex=0.5)
rect.hclust(cosmjer, k=5,border="red")

silueta<-silhouette(cutree(cosmjer,k=5),distancias)
fviz_silhouette(silueta)

"""Para la estrategia al parecer el esmalte es un buen producto para vender con el lápiz de cejas y/o la cosmetiquera para la estrategia faltante (D).

Finalmente,  llevarme las reglas para análisis:
"""

write(rules,file="rules.csv",sep=";",dec=",")

"""##Reglas de asociación como grafos

Vamos a mirar las reglas de asociación como si fuesen grafos. Inicialmente vamos a mirar únicamente las reglas que involucren 2 productos:
"""

rules2<-apriori(cosmetics4,parameter=list(support=0.001,confidence=0.6, maxlen=2))

reglas2<-DATAFRAME(rules2)

"""Creamos variables para graficar después. POr ejemplo, se crea una variable para pintar support en las relaciones (líneas) entre productos(nodos) del grafo"""

reglas2$supclass<-as.factor(ifelse(reglas2$support>0.1,"alto","bajo"))

"""Nodos"""

reglas2$nodos1<-as.character(reglas2$LHS)
reglas2$nodos2<-as.character(reglas2$RHS)
reglas2$liftmax<-reglas2$lift*reglas2$lift

nodostot<-stack(reglas2[,9:10])

nodos<-as.data.frame(unique(nodostot$values))
nodos$parte<-c("ojos","varios","varios","labios","piel","piel","piel","ojos","ojos","ojos","labios","piel","labios","varios")

"""Creamos la red"""

library(igraph)
asocred<-graph_from_data_frame(d=reglas2,vertices=nodos,directed=TRUE)

plot(asocred)

"""Remuevo si la regla va en ambas direcciones, pero es la misma regla."""

asocred2 <- simplify(asocred, remove.multiple = T, remove.loops = F)

plot(asocred2)

plot(asocred2,edge.arrow.size=.01)

plot(asocred2,edge.arrow.size=.01, vertex.label.font=2, vertex.label.dist=0.8)

plot(asocred2,edge.arrow.size=.01, vertex.label.cex=.8, vertex.label.color="black", vertex.label.font=2, vertex.label.dist=0.8)
plot(asocred2,edge.arrow.size=.01, vertex.label.cex=.8, vertex.label.color="black", vertex.label.font=2, vertex.label.dist=0.8, vertex.color="red")

"""Quiero cambiar un parámetro. P.e, support en el color de la linea"""

colorido=c("black","grey")
colorlinea<-colorido[as.numeric(E(asocred2)$supclass)]
plot(asocred2,edge.color=colorido[reglas2$supclass], edge.arrow.size=.01, vertex.label.cex=.8, vertex.label.color="black", vertex.label.font=2, vertex.label.dist=0.8, vertex.color="red")

"""Ahora ancho de linea por lift"""

E(asocred2)$weight<-reglas2$liftmax
plot(asocred2,edge.width=E(asocred2)$weight, edge.arrow.size=.01, vertex.label.cex=.8, vertex.label.color="black", vertex.label.font=2, vertex.label.dist=0.8, vertex.color="red")

"""Ahora color de acuerdo a tipo de cosmetico"""

colorest=c("turquoise3","red3","white","greenyellow")
colorvertice<-colorest[as.numeric(as.factor(V(asocred2)$parte))]

plot(asocred2,edge.color=colorido[reglas2$supclass],edge.width=E(asocred2)$weight, edge.arrow.size=.01, vertex.label.cex=.8, vertex.label.color="black", vertex.label.font=2, vertex.label.dist=0.8, vertex.color=colorvertice[as.factor(nodos$parte)])

"""# **Ejercicio Groceries**

A continuación algunos análisis (en borrador) de la base de datos Groceries, la cual se propone como ejercicio para el estudiante, de modo que luego pueda contrastar con algunos de los análisis aquí expuestos.
"""

data("Groceries")

summary(Groceries)

str(Groceries)

Groceries@itemInfo$labels
Groceries@itemInfo$level1
itemFrequencyPlot(Groceries, topN=50,  cex.names=.5)

"""Reglas"""

rulesg<-apriori(Groceries,parameter=list(support=0.001,confidence=0.6))
summary(rulesg)

"""Los items se ordenan por support aquí"""

cruzadas<-crossTable(Groceries,measure="lift",sort=TRUE)
cruzadas

"""Por un lado los productos a "combinar"
"""

inspect(head(sort(rulesg,by="lift"),20))

"""Por el otro lado los productos que van juntos"""

inspect(head(sort(rulesg,by="support"),20))

"""Gráficos para ver "clusteres" de reglas. Buscar productos con alto lift /support"""

plot(rulesg, measure=c("support","lift"), shading="confidence")

subrulesg<-subset(rulesg,quality(rulesg)$lift>10)
inspect(head(sort(subrulesg,by="support"),20))

"""Vamos a mirar productos centrales. Para facilitar, solo con confidence mayor a 0.7"""

subrulesg2<-subset(rulesg,quality(rulesg)$confidence>0.75)
plot (subrulesg2, method="matrix", measure=c("lift", "support"),
      control=list(reorder='support/confidence'))

"""Grafos"""

subrulesg2a <- head(sort(rulesg, by="support"), 15)
plot(subrulesg2a, method="graph")

plot(subrulesg2a, method="graph", arrowSize=.01)

subrulesg3 <- head(sort(rulesg, by="lift"), 15)
plot(subrulesg3, method="graph")

plot(subrulesg3, method="graph", arrowSize=.01)

"""Producto Final"""

Groceries@itemInfo$labels
rules_producto<-subset(rulesg,subset=lhs %in% "candles")
inspect(head(sort(rules_producto,by="lift"),20))